### ISSUE TITLE
Response close only runs check once.

### ISSUE THREAD

**Issue by Sean1472** [WesJD/AnvilGUI#107]
Hey, when the text doesn't exist, the Response.Close only runs once. 

Here is a video to show;
https://www.dropbox.com/s/t6o0aek1owr9lel/kbCFdWn2rD.mp4?dl=0

Here is the code I tested with;
```java
public void anvilProduceCBResult(Player p) {
        new AnvilGUI.Builder()
                .plugin(ProjectWar.getInstance())
                .onComplete((player, text) -> {
                    String factionName = FactionColl.get().getByName(text) == null ? null : text;
                    if (factionName == null) {
                        return AnvilGUI.Response.text("Faction doesn't exist!");
                    } else {
                        p.sendMessage("Exist!");
                        return AnvilGUI.Response.close();
                    }
                })
                .item(new ItemStack(Material.WRITABLE_BOOK))
                .title("Add CB")
                .text("Enter faction name..")
                .open(p);
    }
```
Easier to view here; https://sourceb.in/318fb7361d
As you can see, it only runs "ttt" once despite it being wrong the second time, as so forth. Does this with any String that is incorrect

Version:
![javaw_qhpQdDkoUy](https://user-images.githubusercontent.com/50555026/91588021-756d3180-e94f-11ea-83e2-09ffeda0a04b.png)

**Comment by portlek** [comment]
can you edit your code like
![image](https://user-images.githubusercontent.com/12835420/91587312-4068db00-e95f-11ea-92f8-436b8cd41f1c.png)

**Comment by Sean1472** [comment]
> can you edit your code like
> ![image](https://user-images.githubusercontent.com/12835420/91587312-4068db00-e95f-11ea-92f8-436b8cd41f1c.png)

Sorry, didn't realize. Updated.

**Comment by portlek** [comment]
can you share your bukkit version?

**Comment by Sean1472** [comment]
> can you share your bukkit version?

![ooinskmx](https://user-images.githubusercontent.com/50555026/91587978-67b7ac00-e94f-11ea-8169-ca7114c5942c.png)
Will also update main post with this image.

**Comment by Sean1472** [comment]
Any news on this by chance? :)

**Comment by WesJD** [comment]
Looks like an issue with another plugin not allowing for closing the anvil.
