### ISSUE TITLE
Broken Maven Dependency

### ISSUE THREAD

**Issue by 7rory768** [WesJD/AnvilGUI#109]
So when I click the link in the README to obtain the maven dependency it says to use the below markup
![image](https://user-images.githubusercontent.com/6015350/94212614-df66f100-fe91-11ea-89e9-450634362e25.png)

Using this markup, the AnvilGUI class is not included. Infact only the 1.10 implementation is included in the project
![image](https://user-images.githubusercontent.com/6015350/94212676-0c1b0880-fe92-11ea-9174-64a3409db597.png)

Going back to my old dependency
```XML
        <dependency>
            <groupId>com.github.WesJD</groupId>
            <artifactId>AnvilGUI</artifactId>
            <version>master-1e9b5d3216-1</version>
        </dependency>
```

I have all the libraries, except for the API library which contains the AnvilGUI class, so I can't compile my code.
![image](https://user-images.githubusercontent.com/6015350/94212805-64520a80-fe92-11ea-8d0b-d7878a16e071.png)
![image](https://user-images.githubusercontent.com/6015350/94212817-6c11af00-fe92-11ea-8b31-fcd0217920c2.png)

Any idea of how to fix this?
I invalidated my caches and restarted my idea but still the issue persists.

**Comment by WesJD** [comment]
I'm not sure why JitPack is showing that as the dependency to include - it is incorrect. This is the correct dependency:
`com.github.WesJD.AnvilGUI:anvilgui:master-SNAPSHOT'`

**Comment by pomtom44** [comment]
Im having the same problem
i think my issue i opened is the same error you have

**Comment by jonahseguin** [comment]
Having this same issue.  Version 1_8_R3

**Comment by Sytm** [comment]
As a temporary fix you can use my maven repository where I always put the latest updates into, because I always had problems with JitPack

```xml
 <repository>
    <id>sytm-nexus</id>
    <url>https://repo.sytm.de/repository/maven-hosted/</url>
 </repository>
```
```xml
<dependency>
    <groupId>net.wesjd</groupId>
    <artifactId>anvilgui</artifactId>
    <version>1.3.0-SNAPSHOT</version>
</dependency>
```

_But today or tomorrow I need to migrate the server so there could still be downtime_

**Comment by portlek** [comment]
I'm using like that;
https://github.com/spigotplugins/anvil-login/blob/master/pom.xml#L75
and I have no issue with that.

**Comment by Sytm** [comment]
But it actually doesnt work @portlek,
just did a quick `mvn clean verify` on your project and while trying to download the deps it could not be resolved
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.058 s
[INFO] Finished at: 2020-09-25T19:35:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project AnvilLogin: Could not resolve dependencies for project io.github.portlek:AnvilLogin:jar:1.3: Could not find artifact com.github.WesJD.AnvilGUI:anvilgui:jar:master-1e9b5d3216-1 in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by portlek** [comment]
It's really weird because this repository
https://github.com/KekoSeries/KekoUtil/blob/master/pom.xml#L141
is completely fine. I can build it.

**Comment by Sytm** [comment]
You probably have them cached in your `~/.m2` repository. If you would delete that folder it would try to download it again and fail.

Or just do `mvn clean verify -U`, which forces -SNAPSHOT updates

**Comment by portlek** [comment]
Alright, I found the bug. I'm solving it.
