### ISSUE TITLE
package net.wesjd.anvilgui does not exist

### ISSUE THREAD

**Issue by pomtom44** [WesJD/AnvilGUI#110]
Hiya
Went to update my plugin and found it no longer compiled.
Went to check the maven dependancy and saw it was different so change it over but no luck
had a look on here and saw the other issue saying about the dependancy, so changed it back, but still not able to compile
Nothing changed on my code with relation to your GUI part, so not sure whats changed to make it fail now

**Comment by portlek** [comment]
Compare you pom file with mine
https://github.com/spigotplugins/anvil-login/blob/master/pom.xml#L75
It's completely fine.
