### ISSUE TITLE
Characters in Output

### ISSUE THREAD

**Issue by JakeValenzuela** [WesJD/AnvilGUI#114]
When creating an AnvilGUI Builder with the latest commit as of now, [f227dcb](https://github.com/WesJD/AnvilGUI/commit/f227dcbf2fd72659aef316197bfee509c9f9fbdf), characters appear in the AnvilGUI output.

Here is a video of the issue occurring:
https://streamable.com/pp8zzh

This issue was tested on a PaperMC 1.8.9 server (I was also using a 1.8.9 client version) using ViaVersion to allow up to 1.16.3 players to join. I tested this problem on a server that was PaperMC 1.15.2 (1.15.2 client) and had ViaVersion and the problem does not occur.

I've used the code given from the example in the readme:
```java          
              new AnvilGUI.Builder()
                    .onClose(player -> {                      //called when the inventory is closing
                        player.sendMessage("You closed the inventory.");
                    })
                    
                    .onComplete((player, text) -> {           //called when the inventory output slot is clicked
                        if (text.equalsIgnoreCase("you")) {
                            player.sendMessage("You have magical powers!");
                            return AnvilGUI.Response.close();
                        } else {
                            return AnvilGUI.Response.text("Incorrect.");
                        }
                    })
                    .text("Test")     //sets the text the GUI should start with
                    .item(new ItemStack(Material.GOLD_BLOCK)) //use a custom item for the first slot
                    .title("Enter your answer.")              //set the title of the GUI (only works in 1.14+)
                    .plugin(instance)                 //set the plugin instance
                    .open(player);                          //opens the GUI for the player provided
        });

**Comment by WesJD** [comment]
What are the characters that are added to the input?

**Comment by Jaaakee** [comment]
You can see in the video that was attached: https://streamable.com/pp8zzh

**Comment by TheKodeToad** [comment]
I think this is caused by the item on the left having formatting (ChatColor.RESET).

**Comment by WesJD** [comment]
Cleaning up issues. Hopefully the above fixes your issue.
