### ISSUE TITLE
The dependency doesn't install

### ISSUE THREAD

**Issue by Nikotecnology** [WesJD/AnvilGUI#116]
Hi, i was trying to use anvilgui with your dependency but i can't install it! i inserted the repository and the dependency into the pom.xml file but when i do mvn clean install it says this warning: "anvilgui-master-f227dcbf2f-1.jar, testanvilgui-1.0.jar define 1 overlapping resource: 
 META-INF/MANIFEST.MF
maven-shade-plugin has detected that some class files are
present in two or more JARs. When this happens, only one
single version of the class is copied to the uber jar.
Usually this is not harmful and you can skip these warnings,
otherwise try to manually exclude artifacts based on
mvn dependency:tree -Ddetail=true and the above output.
See http://maven.apache.org/plugins/maven-shade-plugin/
"
And then if i try using the dependency it doesen't work! how i can do?

In the pom.xml says this error:
"Dependency 'com.github.WesJD.AnvilGUI:anvilgui-1_15_R1:f227dcbf2f' not found

My pom.xml file: https://pastebin.com/GV3ZyYNU

**Comment by portlek** [comment]
```xml
<dependency>
  <groupId>com.github.WesJD.AnvilGUI</groupId>
  <artifactId>anvilgui</artifactId>
  <version>f227dcbf2f</version>
</dependency>
```
you can use the latest commit.

**Comment by Nikotecnology** [comment]
Ok ill'try

**Comment by Nikotecnology** [comment]
ok it works thanks!
