### ISSUE TITLE
1.16.3 support

### ISSUE THREAD

**Issue by Azim** [WesJD/AnvilGUI#117]
sorry that i cant write the wrapper myself

**Comment by portlek** [comment]
The project should work on 1.16.3. have you ever try?

**Comment by Azim** [comment]
had some weird error i didnt record unfortunately, which seemed to fix itself overtime, i'll write back if it repeats

**Comment by Majekdor** [comment]
If you try to run it on a server that runs Spigot 1.16.3 you just get an error message in the console saying AnvilGUI doesn't support this version of Minecraft.

**Comment by blitzdose** [comment]
> If you try to run it on a server that runs Spigot 1.16.3 you just get an error message in the console saying AnvilGUI doesn't support this version of Minecraft.
> 
> Edit: I lied it's working now

How do you fixed it? I'm still getting the error.
