### ISSUE TITLE
Gradle cannot find dependency

### ISSUE THREAD

**Issue by AoElite** [WesJD/AnvilGUI#119]
Yesterday everything was working and now, with no changes, Gradle cannot find the dependency. Over the past few months, I've used many dependencies and this one by far has the most issues with Gradle. I don't know if it's Jitpack or what the problem is, but it seems this happens way too often with this specific dependency.

Using [this](https://jitpack.io/#WesJD/AnvilGUI/master-SNAPSHOT) as specified on the Github

**Comment by portlek** [comment]
Use `master-61aa6d8080-1` as version.

**Comment by WesJD** [comment]
Please use the CodeMC repo which will resolve all JitPack instability.
