### ISSUE TITLE
Can't open menus due to #close()

### ISSUE THREAD

**Issue by TheSilentPro** [WesJD/AnvilGUI#124]
Currently there is no way to open an inventory with the builder as you need to return a response.
Returning #close() closes any menus that are opened

**Comment by WesJD** [comment]
You can run your open method a tick later. However, it would be nice to add something like `Response.openOtherInventory(Inventory)` so people wouldn't have to do that.

**Comment by TheSilentPro** [comment]
This is the error i get when i open another inventory. The other inventory opens okay but anvilgui prints error
Error: https://hastebin.com/ahukozomov.apache
Code: https://hastebin.com/wobiducepa.coffeescript

**Comment by TheSilentPro** [comment]
Any ETA on when this will be done?
