### ISSUE TITLE
onComplete not triggering

### ISSUE THREAD

**Issue by period** [WesJD/AnvilGUI#128]
I've copied over the full example found at the bottom of the readme, although I can't seem to get onComplete to trigger.

My understanding is that once the output (i.e. the right) slot is clicked, it's supposed to trigger although I'm not getting any kind of response.

Clicking on the iron sword/ingot both correctly trigger and send the sword/ingot chat message.

Version: This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
running behind bungeecord

Client version is 1.12.2, ViaVersion is not installed.

**Comment by PikaMug** [comment]
In the GUI, there are three slots - the "left" (first) slot, the "right" (second) slot, and the result (third) slot. Clicking an item in the result/third slot is what triggers onComplete.

That said, the example you followed is flawed. An item will only appear in the third slot if the IRON_SWORD is damaged. This is how genuine Anvils work as well. You could accomplish this by casting the ItemStack to Damageable and getting its ItemMeta, then use the `setDamage` method and apply the new meta to the stack.

Alternatively, you could simply not put anything in the right/second slot. This will also populate the result slot. It's how the library worked for a long time before `item` was split into `itemLeft` and `itemRight` methods.
