### ISSUE TITLE
onComplete not being called because the output slot is empty?

### ISSUE THREAD

**Issue by SnickoDeadMC** [WesJD/AnvilGUI#135]
Hey there, I can't get the onComplete code to run using the example code:

`new AnvilGUI.Builder()
    .onClose(player -> {                                        //called when the inventory is closing
        player.sendMessage("You closed the inventory.");
    })
    .onComplete((player, text) -> {                             //called when the inventory output slot is clicked
        if(text.equalsIgnoreCase("you")) {
            player.sendMessage("You have magical powers!");
            return AnvilGUI.Response.close();
        } else {
            return AnvilGUI.Response.text("Incorrect.");
        }
    })
    .preventClose()                                             //prevents the inventory from being closed
    .text("What is the meaning of life?")                       //sets the text the GUI should start with
    .itemLeft(new ItemStack(Material.IRON_SWORD))               //use a custom item for the first slot
    .itemRight(new ItemStack(Material.IRON_INGOT))              //use a custom item for the second slot
    .onLeftInputClick(player -> player.sendMessage("sword"))    //called when the left input slot is clicked
    .onRightInputClick(player -> player.sendMessage("ingot"))   //called when the right input slot is clicked
    .title("Enter your answer.")                                //set the title of the GUI (only works in 1.14+)
    .plugin(myPluginInstance)                                   //set the plugin instance
    .open(myPlayer);                                            //opens the GUI for the player provided`

I looked into your code and there was this in the InventoryClickEvent:

` if (event.getRawSlot() == Slot.OUTPUT) {
                    final ItemStack clicked = inventory.getItem(Slot.OUTPUT);
                    if (clicked == null || clicked.getType() == Material.AIR) return;`

The inventory loads with no item in the slot so is it just returning before it can get the output slot click?

**Comment by WesJD** [comment]
Well yes, the user clicking on the empty complete slot should not call onComplete. If the completion slot is empty, they have not modified the text of the item yet.

**Comment by SnickoDeadMC** [comment]
> Well yes, the user clicking on the empty complete slot should not call onComplete. If the completion slot is empty, they have not modified the text of the item yet.

I’m not sure if it’s intentional then but when I type something in to modify the text and click the empty slot, nothing happens

**Comment by WesJD** [comment]
Ah, I should really fix this example. It sucks. I did not write this example, and the person who did decided to put two items of different types in the two slots. In order for an item to show up in the result slot, both of the item types need to match (to Minecraft, they are being "combined"). I apologize for that. If you remove the `itemRight` from the example, you'll see how the library works.

**Comment by WesJD** [comment]
Fixed in latest commit.

**Comment by SnickoDeadMC** [comment]
Legend. Thanks mate!
