### ISSUE TITLE
onComplete Bug?

### ISSUE THREAD

**Issue by Rich-a-rd** [WesJD/AnvilGUI#137]
Since a few days somehow the text output is a Component as String. Example:
TextComponentImpl{content="dadwdwdadwa", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}

Java 16, Gradle 7.0, Minecraft 1.16.5, Paper 1.16.5

Code:
```java
new AnvilGUI.Builder().onComplete((executor, text) -> {
                    System.out.println(text);
                    Sign sign = signEditorSign.get(player);
                    sign.line(line, Component.text(text));
                    sign.update();
                    player.sendMessage(ServerSystem.prefix + "Du erfolgreich die §aLine§8: §a" + (line + 1) + " §bin §a" + text + "umbenannt.");
                    return AnvilGUI.Response.close();
                }).text(((TextComponent) signEditorSign.get(player).line(line)).content())
                        .itemLeft(new ItemStack(Material.OAK_SIGN))
                        .title("§bLine " + (line + 1) + " Umbennung")
                        .plugin(ServerSystem.getInstance())
                        .open(player);
```

**Comment by WesJD** [comment]
What build of paper are you on?

**Comment by Rich-a-rd** [comment]
682 (release 16.05.2021)

**Comment by Rich-a-rd** [comment]
Do you have any idea. It would be amazing if I can use this again.

**Comment by WesJD** [comment]
I cannot reproduce this issue on the latest version of paper. Perhaps try updating?

**Comment by Rich-a-rd** [comment]
I've tried it again. It works again. I'm really confused. But thank you for your help.
