### ISSUE TITLE
Add compatibility for 1.7.10

### ISSUE THREAD

**Issue by Maymity** [WesJD/AnvilGUI#14]
Can you add support for 1.7.10?

**Comment by Miclebrick** [comment]
Get off your dinosaur and get on this rocket ship™

**Comment by WesJD** [comment]
I'll see what I can do.

**Comment by WesJD** [comment]
unfortunately supporting 1.7 is an absolute pain since it is not supported by build tools.

**Comment by Selim042** [comment]
http://howoldisminecraft1710.today/
