### ISSUE TITLE
NPE with itemstack AIR

### ISSUE THREAD

**Issue by ExplosiveMine** [WesJD/AnvilGUI#140]
[https://github.com/WesJD/AnvilGUI/blob/master/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java](url)

        if (itemText != null) {
            if (inputLeft == null) {
                this.inputLeft = new ItemStack(Material.PAPER);
            }
            ItemMeta paperMeta = this.inputLeft.getItemMeta();
            paperMeta.setDisplayName(itemText);
            this.inputLeft.setItemMeta(paperMeta);
        }

For an itemstack created with `Material.AIR`, this ->

    if (inputLeft == null) {

returns false. However `paperMeta` does not have a display name and this causes a npe

This also causes it to be impossible to make an anvil with no items in both slots as this ->

        if (itemText != null) {

cannot be bypassed since `itemText` cannot actually be null as its validated

    Validate.notNull(text, "Text cannot be null");

**Comment by WesJD** [comment]
Sure, I can add a check for AIR, but I really don't think that's the issue here. This library is never meant to have air in that slot.
