### ISSUE TITLE
Wrapper 1.17

### ISSUE THREAD

**Issue by xIrinaShaykx** [WesJD/AnvilGUI#141]
Can u pls update to 1.17?

**Comment by portlek** [comment]
working on it.

**Comment by portlek** [comment]
currently codemc's nms repository has not the 1.17 jar file.

there is 1.17 in it but it has not jar file tho
![image](https://user-images.githubusercontent.com/12835420/121703505-94eada80-cadb-11eb-9403-244dd5610d8b.png)

**Comment by xIrinaShaykx** [comment]
@portlek look at ur mails i wrote u smth. I dont know if that can help u out

**Comment by portlek** [comment]
> smth

hope, codemc's nms repository should fix that. we should not add more repositories to the project. codemc's nms repository is enough to make it but we just need to wait it.

**Comment by xIrinaShaykx** [comment]
k
