### ISSUE TITLE
Repository doesn't have 1.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by tchristofferson** [WesJD/AnvilGUI#144]
The repository doesn't contain the 1.5.1-SNAPSHOT which includes the 1.17 code.
![image](https://user-images.githubusercontent.com/17221639/121833677-7844d300-cc92-11eb-9bf5-b07ea84e2ec0.png)

**Comment by PikaMug** [comment]
You could use [Jitpack](https://jitpack.io/#WesJD/AnvilGUI) for now (although I'm personally waiting until #143 is merged).

**Comment by WesJD** [comment]
The CodeMC jenkins is currently having wacky issues building the 1.17 module. I am waiting for a response from them.

**Comment by mmuziek** [comment]
currently even jitack reports no artifacts found:
![image](https://user-images.githubusercontent.com/1270969/121914153-4e42ed80-cd32-11eb-94fb-df3693391424.png)
i tried multiple versions the from the codemc repo aswell as the jitpack
both arent providing any artifacts at all.

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/121915035-7f73eb80-cd3b-11eb-8a1d-811d5277763b.png)
it isn't built yet. you have to click the get it button and wait it until the building finish.

**Comment by portlek** [comment]
there you go
```xml
<dependency>
  <groupId>com.github.WesJD</groupId>
  <artifactId>AnvilGUI</artifactId>
  <version>-f45716e252-1</version>
</dependency>
```

**Comment by portlek** [comment]
But it can't build because the project's java version has changed. so it complains about the version of the jdk
![image](https://user-images.githubusercontent.com/12835420/121915554-fd37f700-cd3b-11eb-9fd7-aa9ab35e473f.png)

**Comment by mmuziek** [comment]
> there you go
> 
> ```
> <dependency>
>   <groupId>com.github.WesJD</groupId>
>   <artifactId>AnvilGUI</artifactId>
>   <version>f45716e252</version>
> </dependency>
> ```

im sorry but that one cannot be found either:
![image](https://user-images.githubusercontent.com/1270969/121923937-b813c500-cd3b-11eb-9f0c-bc99732d7f13.png)
![image](https://user-images.githubusercontent.com/1270969/121923957-bea23c80-cd3b-11eb-89ae-798b90164fed.png)

**Comment by portlek** [comment]
@mmuziek yes because the repository can't build. we have to fix the build script.

**Comment by mmuziek** [comment]
any news on this matter yet. all my projects are frozen until its solved

**Comment by portlek** [comment]
@WesJD should revert https://github.com/WesJD/AnvilGUI/commit/1fd206c7470021a15ae26cbe058b068c0222c9bc this commit.

**Comment by portlek** [comment]
or another solution, the source and target will move to only 1.17's pom then add java 16 parameter to the jitpack.yml to build on Java 16. but the first solution easier that this :D

**Comment by spnda** [comment]
> @WesJD should revert [1fd206c](https://github.com/WesJD/AnvilGUI/commit/1fd206c7470021a15ae26cbe058b068c0222c9bc) this commit.

Yes I agree. Especially as the switch to Java 16 for compiling does not provide any usefulness to the library. The 1.17 Wrapper does not use any new language features.

**Comment by WesJD** [comment]
Java 16 is required for the 1.17 module to build. Reverting the commit is not a solution.

**Comment by WesJD** [comment]
The CI build issue has been resolved. 1.5.1-SNAPSHOT is now available via codemc. Thanks for your patience.
