### ISSUE TITLE
Maven Shade Error 1.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by tchristofferson** [WesJD/AnvilGUI#145]
The error I am getting when trying to build my plugin:
`Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default) on project Plugin: Error creating shaded jar: Problem shading JAR C:\Users\Trent\workspace\Stocks\Plugin\target\Plugin-1.0-SNAPSHOT.jar entry com/tchristofferson/stocks/commands/StockbrokerCommand.class: java.lang.IllegalArgumentException: Unsupported class file major version 60`
I am using the maven compiler plugin and I set the source and target to 16 and have the Java 16 JDK installed and being used by IntelliJ. I am unsure if the error is because of me or if it is the repository.

**Comment by tchristofferson** [comment]
I think this might be an issue with something else in my project.

**Comment by galacticwarrior9** [comment]
Did you figure out the cause? I'm having the same issue.

**Comment by tchristofferson** [comment]
@galacticwarrior9 you need to use version 3.3.0-SNAPSHOT of the maven shade plugin. You might also need to add the snapshot plugin repository.
