### ISSUE TITLE
still cannot get 1.5.1 from repo

### ISSUE THREAD

**Issue by mmuziek** [WesJD/AnvilGUI#146]
as the title states.
i tried using provided repo and artifact dependency but sadly i get a not found
![image](https://user-images.githubusercontent.com/1270969/122172156-c5869780-ce80-11eb-8d29-2029637b36b2.png)

any idea why this happens?

**Comment by Oskang09** [comment]
maybe try clear cache and run again? it's work fine for me.

**Comment by portlek** [comment]
remove the files from .m2/repository folder.

**Comment by mmuziek** [comment]
well it got added sadly resulted :
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project MCGStarCraft: Compilation failure
[ERROR] /D:/Eclipse workspace/project/src/com/mmuziek/project/util/class.java:[37,26] cannot access net.wesjd.anvilgui.AnvilGUI
[ERROR]   bad class file: C:\Users\m-muz\.m2\repository\net\wesjd\anvilgui\1.5.1-SNAPSHOT\anvilgui-1.5.1-SNAPSHOT.jar(/net/wesjd/anvilgui/AnvilGUI.class)
[ERROR]     class file has wrong version 60.0, should be 58.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] -> [Help 1]

**Comment by portlek** [comment]
you should use java 16

**Comment by mmuziek** [comment]
i am using 16

**Comment by mmuziek** [comment]
well after reinstalling everything i still get a
Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.2:shade (default) on project MCGStarCraft: Error creating shaded jar: Problem shading JAR C:\Users\m-muz\.m2\repository\net\wesjd\anvilgui\1.5.1-SNAPSHOT\anvilgui-1.5.1-SNAPSHOT.jar entry net/wesjd/anvilgui/AnvilGUI.class: java.lang.IllegalArgumentException: Unsupported class file major version 60

**Comment by NathanCollaert** [comment]
I am getting the following error which looks like the one above:
`class file has wrong version 60.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.`

**Comment by Oskang09** [comment]
this is work fine under my repository which target Java 16 and compile to Java 16 too. Those error is because you're not using Java 16, even u have to set compileTarget to Java 16.

**Comment by mmuziek** [comment]
Well explane how a compile target Java 16 using Java 16 SDK on a system with the Java 16 in eclipse That is upgraded to work on Java 16 
Is there anything im missing

**Comment by Oskang09** [comment]
send your pom.xml and all the error logs only us can help you

**Comment by mmuziek** [comment]
https://pastebin.com/Es9KGtuz thats my pom:
and the error : 

Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.2:shade (default) on project project: Error creating shaded jar: Problem shading JAR C:\Users\m-muz\.m2\repository\net\wesjd\anvilgui\1.5.1-SNAPSHOT\anvilgui-1.5.1-SNAPSHOT.jar entry net/wesjd/anvilgui/AnvilGUI.class: java.lang.IllegalArgumentException: Unsupported class file major version 60

**Comment by tchristofferson** [comment]
I had this issue. The problem is with the maven shade plugin. You need to use 3.3.0-SNAPSHOT version of the plugin. I was having the exact same error.

**Comment by mmuziek** [comment]
After a very long hassle the version was indeed the problem.
I had to include the snapshot repository for maven (apache) plugins and then alter the plugin used to the version specified above.
after that it took a while but did build
thanks everyone for your help !

For those who want this solution add this to the pom:
<pluginRepositories>
    <pluginRepository>
      <id>apache.snapshots</id>
      <url>https://repository.apache.org/snapshots/</url>
    </pluginRepository>
  </pluginRepositories>
  and alter the maven shade plugin to version 3.3.0-SNAPSHOT
