### ISSUE TITLE
Java 8 compatibility

### ISSUE THREAD

**Issue by Mezy** [WesJD/AnvilGUI#148]
Hey, I was wondering why the source & target compatibility is not set to Java 8. This way the library could be used in both Java 16 & Java 8 plugins.

**Comment by WesJD** [comment]
Minecraft 1.17 requires the usage of Java 16. For us to have a 1.17 module, we must use Java 16.

**Comment by Mezy** [comment]
I've made a fork and in that changed the source & target compatibility to Java 16 and I can still compile the library.
https://jitpack.io/com/github/Mezy/AnvilGUI/master-ce87a11d32-1/build.log

**Comment by portlek** [comment]
btw, the library don't have to use java 16, it just needs java 16 compatibility.
