### ISSUE TITLE
Spigot 1.8

### ISSUE THREAD

**Issue by KingsMMA** [WesJD/AnvilGUI#152]
The requirements section states a requirement of java 16, but spigot 1.8 plugins won't work with java 16.  How would I be able to use this for a 1.8 server?

**Comment by portlek** [comment]
you should wait for #150

**Comment by KingsMMA** [comment]
Do you know an ETA for when it should come out?

**Comment by portlek** [comment]
idk when @WesJD gonna merge it. but you can clone the project and build it your self with java 8 version.

**Comment by WesJD** [comment]
Fixed in 15bdaabc16599ea205d5bffb1905febbe9d2461f. Thank you for your patience - have been busy IRL.
