### ISSUE TITLE
net/wesjd/anvilgui/AnvilGUI$Response does not exist

### ISSUE THREAD

**Issue by KingsMMA** [WesJD/AnvilGUI#153]
I'm using gradle for a spigot 1.8 plugin.
Whenever I try to load the plugin, I get a warning saying the class mentioned in the title doesn't exist.
I saw some similar issues in the closed issues section, but all the ones I looked at where using Maven, not gradle.

Does anyone know how to fix this?
My only idea is installing an AnvilGUI plugin onto the server, but I couldn't find any.

**Comment by portlek** [comment]
do you use shadowJar to build your project?

**Comment by WesJD** [comment]
Yes, as @portlek mentioned, you need to create some sort of uber jar with the library included.

**Comment by KingsMMA** [comment]
How would I be able to do that?  I've searched on google and tried following a tutorial but I couldn't get it to work

**Comment by portlek** [comment]
install shadowJar plugin then run, gradle shadowJar command.

**Comment by KingsMMA** [comment]
I tried that and it didn't work; it produced a jar with ~1k of data in it with 1 file inside the jar
