### ISSUE TITLE
Question: 1.17 & java 16

### ISSUE THREAD

**Issue by TheSilentPro** [WesJD/AnvilGUI#154]
So i noticed that 1.17 wrapper was already added and changes from java 16 were reverted as of writing this.
Will there be a version release with 1.17 support compiled in java 8 (since the revert)?
Will AnvilGUI just support 1.17 and Java 16?

**Comment by portlek** [comment]
yes it should.

**Comment by WesJD** [comment]
Yes, that is correct. Java is backwards compatible. In the process of resolving the compilation errors, I had thought that Java 16 was required to be the target version. However, the source just needs to be compiled using Java 16 with a target version of 8.
