### ISSUE TITLE
Not able to compile on 1.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by freppp** [WesJD/AnvilGUI#156]
Project SDK is set to Java 8. Both source and target are set to Java 8, yet everytime I compile I'm left with 

ERROR]   bad class file: C:\Users\a\.m2\repository\net\wesjd\anvilgui\1.5.1-SNAPSHOT\anvilgui-1.5.1-SNAPSHOT.jar(net/wesjd/anvilgui/AnvilGUI.class)
[ERROR]     class file has wrong version 60.0, should be 52.0

Any help is appreciated. Thanks

**Comment by WesJD** [comment]
You need to use Java 16 to compile.

**Comment by freppp** [comment]
> You need to use Java 16 to compile.

Same issue persists when compiling with 16

**Comment by WesJD** [comment]
Then you are not actually compiling with Java 16. Check your JAVA_HOME. That error only occurs due to the 1.17 server begin built with Java 16. The CI server uses Java 16 as well and is compiling correctly.

**Comment by Drc-DEV** [comment]
Having the same issue with 1.5.3-SNAPSHOT with maven shade
Unsupported class file major version 60
Java version: 16.0.1, vendor: N/A, runtime: /usr/lib/jvm/java-16-openjdk
