### ISSUE TITLE
No fixed builds on CodeMC repository

### ISSUE THREAD

**Issue by spnda** [WesJD/AnvilGUI#157]
Even though 15bdaab was built through Jenkins, the class files on the maven repository (https://repo.codemc.io/repository/maven-public/net/wesjd/anvilgui/1.5.1-SNAPSHOT/anvilgui-1.5.1-20210705.155110-3.jar), are still compiled as Java 16.
The same is also true for the anvilgui-1.5.1-SNAPSHOT.jar I got from https://ci.codemc.io/job/WesJD/job/AnvilGUI/25/.

The freshly downloaded jar's `AnvilGUI.class` file still reports as version 60.
```
> javap -verbose "AnvilGUI.class"
Classfile /C:/Users/sean1/Desktop/AnvilGUI.class
  Last modified 15 Jun 2021; size 7399 bytes
  SHA-256 checksum c39c2937d5bc7e7f94096f60fce5b07a5ca9c9c12a7ae7941919210ad2b3cd29
  Compiled from "AnvilGUI.java"
public class net.wesjd.anvilgui.AnvilGUI
  minor version: 0
  major version: 60
```

Should we maybe bump the version to 1.5.2 as well?

**Comment by portlek** [comment]
its fixed already

https://repo.codemc.io/repository/maven-snapshots/net/wesjd/anvilgui-parent/1.5.1-SNAPSHOT/anvilgui-parent-1.5.1-20210705.155001-8.pom

![image](https://user-images.githubusercontent.com/12835420/124760392-5f4ddb80-df39-11eb-9aa4-7f616db49d30.png)

it should work.

you can use 1.5.1-SNAPSHOT.

**Comment by spnda** [comment]
It **should** but it **doesn't**. Have you even tried downloading https://repo.codemc.io/repository/maven-public/net/wesjd/anvilgui/1.5.1-SNAPSHOT/anvilgui-1.5.1-20210705.155110-3.jar and checking what major file version you get, before commenting that it "should" work? Cause it's 60 (Java 16). You can download any of the 1.5.1-SNAPSHOT JARs and all of them will report with class file major 60. (`javap -verbose AnvilGUI.class`).

**Comment by portlek** [comment]
did you clear your .m2 folder's a.k.a. cache?

**Comment by spnda** [comment]
How does that have any relation to this issue? I'll give you a walkthrough of what you have to do, so that you understand what I mean:
1. Download the file at https://repo.codemc.io/repository/maven-public/net/wesjd/anvilgui/1.5.1-SNAPSHOT/anvilgui-1.5.1-20210705.155110-3.jar (or the latest 1.5.1-SNAPSHOT, but this should be it).
2. Extract the JAR using 7-zip or similar.
3. Navigate to net/wesjd/anvilgui in the folder.
4. Run `javap -verbose AnvilGUI.class` whereever you extracted the JAR

If you would have done these steps or checked yourself, you would have noticed this quicker. The files are simply compiled with JDK 16.
```
PS C:\Users\sean1\Desktop> javap -verbose AnvilGUI.class
Classfile /C:/Users/sean1/Desktop/AnvilGUI.class
  Last modified 15 Jun 2021; size 7399 bytes
  SHA-256 checksum c39c2937d5bc7e7f94096f60fce5b07a5ca9c9c12a7ae7941919210ad2b3cd29
  Compiled from "AnvilGUI.java"
public class net.wesjd.anvilgui.AnvilGUI
  minor version: 0
  major version: 60
```

**Comment by joestr** [comment]
I can confirm @spnda's issue, but I resolved it by running `mvn clean install` against the repo.

**Comment by spnda** [comment]
I can confirm @joestr, running `mvn clean install` does provide fixed builds in my .m2 repository. So a basic rebuild for the Jenkins and CodeMC repository might be sufficient for having the fixed builds be public.

**Comment by Chasewhip8** [comment]
Can confirm ran into this problem a bit ago.

**Comment by vance13** [comment]
> I can confirm @joestr, running `mvn clean install` does provide fixed builds in my .m2 repository. So a basic rebuild for the Jenkins and CodeMC repository might be sufficient for having the fixed builds be public.

when I try to clean install, I get this error:

cannot access net.wesjd.anvilgui.AnvilGUI
  bad class file: /Users/vance/.m2/repository/net/wesjd/anvilgui/1.5.1-SNAPSHOT/anvilgui-1.5.1-SNAPSHOT.jar(net/wesjd/anvilgui/AnvilGUI.class)
    class file has wrong version 60.0, should be 52.0
    
How did you fix this? I'm new to maven and dependencies

**Comment by vance13** [comment]
same issue

**Comment by vance13** [comment]
> same issue, I'm having trouble fixing it as clean install just compiles the project with the same version

only way i could fix it was by opening the project in intellij, going to project structure and changing the language level/compile version/module version, and recompiling

**Comment by WesJD** [comment]
739cf343f8148f33b373d87add430f2dfc91e729 should resolve this issue. I assume it was a caching issue on the codemc side.

**Comment by spnda** [comment]
@WesJD Yes, that did in fact fix the issue. Thank you!
