### ISSUE TITLE
Ability to set custom Result item

### ISSUE THREAD

**Issue by SuperRonanCraft** [WesJD/AnvilGUI#159]
I was wondering since I'm making a custom coded RPG plugin. I want a cool looking way to install a "Catalyst" (modifier) on a weapon, and this was the closest library I've seed to do this, but I need a little more control. Would this be possible?

Example:
![image](https://user-images.githubusercontent.com/7385626/126878876-6c8ba02e-990b-4e3c-97c3-4fff89cb9843.png)

**Comment by WesJD** [comment]
You would not be able to get the X covering the arrow to go away from the client, ever. If you're fine with that, then yes it is possible, and you just need to PR an extra builder method to place an item in the result slot.
