### ISSUE TITLE
Anvil takes XP from player when the result slot is clicked

### ISSUE THREAD

**Issue by TeenKraken** [WesJD/AnvilGUI#160]
I saw there was a previous issue(#29) with the same problem as mine, and it was apparently fixed for those versions, but now it is back.
I am using MC version 1.17.1
The Issue:
If a player has experience levels, it will be taken when using the Anvil GUI, and if a player doesn't have enough experience, it will not be taken.

I've tried fixing it manually by adding 1 XP level to the player when he finishes using the anvil using .onComplete for compensation, but for some reason, it adds more than 1 level, making an XP dupe glitch. I've also tried saving the player XP before using the anvil and then reapplying it after using it, but that doesn't do anything.

It would also be cool to turn this bug into a feature, and have an option to configure XP costs or to completely disable them.
Thanks in advance!

EDIT:
I found a temporal fix by adding this line of code near the end before closing the GUI:
`player.giveExpLevels(0);`
There seems to be some code inside the Anvil GUI that DOES add 1 xp level to compensate it, but for some reason, it only gets activated if you manually use player.giveExpLevels. This is why before it added 2xp levels instead of 1, and so setting it to 0, will only give you 1 level.

**Comment by spnda** [comment]
Can confirm this is indeed an issue on 1.17.1. It is easily fixable using this snippet, note however that the client may render less XP for a short time.
```java
private void openAnvilGUI() {
    (new AnvilGUI.Builder())
        // the rest of your stuff
        .onClose(this::onCloseCallback);
}

private void onCloseCallback(final Player player) {
    player.giveExpLevels(0);
}
```

**Comment by nik2143** [comment]
Seems that the reason is that on version 1.17.1 the method is changed and is no longer this https://github.com/WesJD/AnvilGUI/blob/53253b993e4c950f232752bbcb2bb55ce2492cb2/1_17_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_17_R1.java#L128 but is l()
