### ISSUE TITLE
AnvilGUI result string

### ISSUE THREAD

**Issue by PixelsDE** [WesJD/AnvilGUI#161]
Hi Wesley, 
well how should I start. My name is Carina, Im german and Ive integraded or mostly copied your AnvilGUI (Minecraft) into my project. I want to get the String that the Player has entered to set the itemname to but I dont know how to get the string or how to return the string. Meaining if I enter like „hello“ into the NameBar and than klick the resultSlot well how can I get the String the Player has entered. Cause I dont want to send the Player any text or so just want to get the „new“ itemstack Name.
I would be Pretty happy about an answer,
regards Carina

**Comment by WesJD** [comment]
I wish I had the time to teach you how to code, but I don't. I recommend posting on the Spigot forum, or just a basic Java forum, for finding help on this.
