### ISSUE TITLE
Problem on compile

### ISSUE THREAD

**Issue by ImDxni** [WesJD/AnvilGUI#162]
Hi, i'm trying to compile this with a java version below 16 with gradle but it still says me "Unsupported class file major version 60"

**Comment by joestr** [comment]
Maybe you have picked that information up wrong, but you _have_ to compile it with with Java 16. It states that [here](https://github.com/WesJD/AnvilGUI#compilation).

**Comment by ImDxni** [comment]
> Maybe you have picked up that information wrong, but you _have_ to compile it with with Java 16. It states that [here](https://github.com/WesJD/AnvilGUI#compilation).

But [here](https://github.com/WesJD/AnvilGUI#requirements) is written that i need at least java 8 (im not trying to compile the project, im just using it as library)

**Comment by byteful** [comment]
Same problem for me. I'm trying to use it as a library but I'm using Java 8 for better compatibility with older MC versions. I guess I have to compile a Java 8 compatible version of this.

**Comment by ByteExceptionM** [comment]
Same problem here, using `1.5.2-SNAPSHOT`

**Comment by thenilsdev** [comment]
Without https://github.com/WesJD/AnvilGUI/blob/53253b993e4c950f232752bbcb2bb55ce2492cb2/1_17_R1/pom.xml#L30-L42 everything works as expected when building with java 16 and running on java 8 server. Setting target and source to 16 requires everyone to use java 16 as minimum

**Comment by WesJD** [comment]
> Without
> 
> https://github.com/WesJD/AnvilGUI/blob/53253b993e4c950f232752bbcb2bb55ce2492cb2/1_17_R1/pom.xml#L30-L42
> 
> everything works as expected when building with java 16 and running on java 8 server. Setting target and source to 16 requires everyone to use java 16 as minimum

This is incorrect. I have compiled the library using java 16 locally, built a plugin using java 8, and ran the plugin using java 8, all without any issue with the recent `1.5.3-SNAPSHOT` release. Please try this release to see if it resolves your issues.

**Comment by thenilsdev** [comment]
Did you add the jar via system scope in maven or via IDE? When I add the library as compile scope, maven complains.
