### ISSUE TITLE
Unable to compile version 1.2-SNAPSHOT

### ISSUE THREAD

**Issue by JustDJplease** [WesJD/AnvilGUI#17]
Hey there!

I am running into an issue whilst trying to compile my own plugin. I have a rather small understanding of maven, as I am still starting out and therefore I was unable to solve this problem:

`Failed to execute goal on project sounds: Could not resolve dependencies for project me.theblockbender.nature:sounds:jar:0.1-SNAPSHOT: Failed to collect dependencies at net.wesjd:anvilgui:jar:1.2-SNAPSHOT: Failed to read artifact descriptor for net.wesjd:anvilgui:jar:1.2-SNAPSHOT: Could not find artifact net.wesjd:anvilgui-parent:pom:1.2-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]`

I have all the spigot dependencies installed on my local repository. I made sure of that. You can find my POM file here: https://github.com/JustDJplease/NatureSounds/blob/master/pom.xml. Any suggestions as to what I am doing wrong?

**Comment by WesJD** [comment]
try again now. with the new project structure, I deployed just api and not the entire project by accident.

**Comment by JustDJplease** [comment]
Works like a charm. Thank you for this amazing API!
