### ISSUE TITLE
Error on open()

### ISSUE THREAD

**Issue by zrll12** [WesJD/AnvilGUI#170]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}

Server version: mohist-1.16.5-318
java version: jdk-11

My code is:
new AnvilGUI.Builder()
                            .onClose(player -> {
                                player.sendMessage(HelloMinecraft.config.getString("lang.inputfailed", "You have closed the interface, charge failed"));
                            })
                            .onComplete((player, text) -> {
                                if(text.isBlank()){
                                    return AnvilGUI.Response.text(HelloMinecraft.config.getString("lang.noinput", "No input detected."));
                                }
                                player.chat("/charge " + tid + " " + text);
                                return AnvilGUI.Response.close();
                            })
                            .itemLeft(leftstack)
                            .itemRight(rightstack)
                            .title(HelloMinecraft.config.getString("lang.inputamount", "Input the amount below"))
                            .plugin(HelloMinecraft.instance)
                            .open(e.getPlayer());

**Comment by WesJD** [comment]
You need to shade this library into your plugin. There are directions on how to do so in the README.md.
