### ISSUE TITLE
Error in versions compatibility

### ISSUE THREAD

**Issue by vin27dev** [WesJD/AnvilGUI#171]
`anvilgui/version/Wrapper1_17_R1 has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
This error appears with my plugin compiled in Java 8 and spigot version 1.8.8. Please fix that!

**Comment by WesJD** [comment]
This issue has been resolved with release `1.5.3-SNAPSHOT`.
