### ISSUE TITLE
[Error] error: package net.wesjd.anvilgui does not exist import net.wesjd.anvilgui.AnvilGUI;

### ISSUE THREAD

**Issue by LukePfister00** [WesJD/AnvilGUI#174]
Good day, I use Gradle( as that is the source code for a plugin) however when adding the plugin as a dependency I get the following error when following jitpack's instructions

error: package net.wesjd.anvilgui does not exist
import net.wesjd.anvilgui.AnvilGUI;

**this is the repo url** 
maven { url 'https://jitpack.io' }

**and this is the dependency link**
implementation 'com.github.WesJD.AnvilGUI:anvilgui-1_10_R1:-SNAPSHOT'

any idea what i am doing wrong?

Thanks

**Comment by WesJD** [comment]
You need to shade the library into your plugin.
