### ISSUE TITLE
Could not use any other items except IRON_SWORD in Anvil Gui (1.16.5)

### ISSUE THREAD

**Issue by RobyFasa** [WesJD/AnvilGUI#178]
**new AnvilGUI.Builder()
                        .onClose(player -> p.sendMessage("chiuso"))
                        .onComplete((player, text) -> {
                            player.sendMessage(text);
                            return AnvilGUI.Response.close();
                        })
                        .text("Digita ")
                        .plugin(instance)
                        .itemLeft(new ItemStack(Material.IRON_SWORD))
                        .itemRight(new ItemStack(Material.IRON_SWORD))
                        .open(p);**

                        
If i put any other item, like Material.PAPER, anvil gui doesn't work.

**Comment by Sytm** [comment]
I can't test right now if that is really a problem using different items, but if you omit the calls on `itemLeft` and `itemRight` you will get a `PAPER` as the item by default in the left slot only (in case that is what you want)

**Comment by WesJD** [comment]
The item types need to be able to be combined in a regular anvil.
