### ISSUE TITLE
Huge dependency size

### ISSUE THREAD

**Issue by mastercake10** [WesJD/AnvilGUI#18]
I've been using this API for years now, but the newest update goes beyond the size of 300kb when compiled.
Could you please create a minimized version of it, without using Classgraph? I don't think that Classgraph is really needed here for such a small minecraft library.

Thanks!

**Comment by WesJD** [comment]
Fair point - I was redesigning the project and that's just the first thing that came to mind. I can get an update out soon that's using an enum instead. Thanks for the catch!

**Comment by WesJD** [comment]
Released under `1.2.1-SNAPSHOT`.
