### ISSUE TITLE
Upload version for 1.18 to repository.

### ISSUE THREAD

**Issue by arturekdev** [WesJD/AnvilGUI#182]

**Comment by Sytm** [comment]
Its already [uploaded](https://repo.codemc.io/#browse/browse:maven-public:net%2Fwesjd%2Fanvilgui%2F1.5.3-SNAPSHOT%2F1.5.3-20211201.153432-3%2Fanvilgui-1.5.3-20211201.153432-3.jar). The version is still `1.5.3-SNAPSHOT`.

**Comment by arturekdev** [comment]
Thanks ❤️
