### ISSUE TITLE
1.18.1 support

### ISSUE THREAD

**Issue by mmuziek** [WesJD/AnvilGUI#184]
hey man any chance to allow 1.18.1 in the gui system :) currently it states unsupported version

**Comment by WesJD** [comment]
Finals week for me - won't be able to add support until next week. Please submit a PR to add it if you can and I'll merge.

**Comment by Sytm** [comment]
But Minecraft 1.18.1 is already working.

I guess NMS didn't change this minor update, so all good

**Comment by mmuziek** [comment]
it is working until you use the GUI it trows a error and blocks the plugin further states unsupported version 1.18.1
14.12 08:20:51 [Server] INFO Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
this happens on 1.18.1 and not in 1.18

**Comment by Sytm** [comment]
I just tried it again on
> This server is running CraftBukkit version 3368-Spigot-8965a50-2a2caa7 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
with [this test plugin](https://github.com/WesJD/AnvilGUI/files/7739618/test-plugin.zip) and it works flawless

**Comment by mmuziek** [comment]
sytm i tried it aswell and it blocks 1.18.1 so i wonder can u send me  the import in maven u have?

**Comment by Sytm** [comment]
Well, [this](https://repo.codemc.io/#browse/browse:maven-public:net%2Fwesjd%2Fanvilgui%2F1.5.3-SNAPSHOT%2F1.5.3-20211201.153432-3%2Fanvilgui-1.5.3-20211201.153432-3.jar) is the actual file in the maven repository and it works for me.

Not sure if this is the cause of your problems, but maybe try deleting AnvilGUI from your local maven repository by deleting the folder `~/.m2/repository/net/wesjd/`.

And if you are using Gradle maybe also look at [this](https://stackoverflow.com/a/13567793).
