### ISSUE TITLE
New versioning scheme

### ISSUE THREAD

**Issue by Sytm** [WesJD/AnvilGUI#186]
Because this library uses NMS I propose a new versioning scheme that uses the currently supported Minecraft version:

So at the moment this would be `1.18.0.0` because the library had to be updated to Minecraft `1.18`.

Now we publish a bug fix the version would be bumped to `1.18.0.1`.

Now Minecraft `1.18.1` did not require a fix in this library, so the version stays at `1.18.0.1`.

Now we publish a bug fix the version would be bumped to `1.18.1.0`.

Now Minecraft `1.18.2` requires a fix in this library, so the version is bumped to `1.18.2.0`.

Now we publish a bug fix the version would be bumped to `1.18.2.1`.

---
And on a side-note, if we would use Gradle, updating the version would require updating it in only one file.

**Comment by WesJD** [comment]
Sorry that I have just gotten around to responding to this issue. I agree with @joestr that this versioning scheme does not fit the project structure. Is there something wrong with the current versioning scheme? Furthermore, I would not like to use Gradle for this project - the additional complexity is not needed for a project this simple in my opinion.
