### ISSUE TITLE
How can I add this to my project?

### ISSUE THREAD

**Issue by AW1534** [WesJD/AnvilGUI#187]
I'm a completely new Java programmer with experience in only C#, javascript and python.

I made a plugin following a tutorial, and now I'm working on my own project. but I don't understand how I can add this to my plugin.

can someone help me, please? I don't know where to start. I added maven to my IntelliJ project by right-clicking on the project and clicking "Add framework support", but when I copy the snippet from the readme into my pom.xml (shown below*) IntelliJ shows me this 
![image](https://user-images.githubusercontent.com/62200778/147852298-7f600ec1-bb27-4936-8c1a-cbbf3d95b5a9.png)

but if i remove that `<dependency>` part, IntelliJ now shows me this
![image](https://user-images.githubusercontent.com/62200778/147852332-81ff116b-320b-49ac-97bf-c39b83aafb66.png)

_*The snippet:_

```
<dependency>
    <groupId>net.wesjd</groupId>
    <artifactId>anvilgui</artifactId>
    <version>1.5.3-SNAPSHOT</version>
</dependency>

<repository>
    <id>codemc-snapshots</id>
    <url>https://repo.codemc.io/repository/maven-snapshots/</url>
</repository>
```

**Comment by portlek** [comment]
```xml
<dependencies>
  <dependency>
      <groupId>net.wesjd</groupId>
      <artifactId>anvilgui</artifactId>
      <version>1.5.3-SNAPSHOT</version>
  </dependency>
</dependencies>
```

**Comment by AW1534** [comment]
damn, this was a fast answer, thanks. but now I have a couple more questions IntelliJ now says this: 
![image](https://user-images.githubusercontent.com/62200778/147852424-f890af45-6d73-4455-9535-00223dd35d24.png)
