### ISSUE TITLE
AnvilGUI$Response does not exist.

### ISSUE THREAD

**Issue by Eccessiv0** [WesJD/AnvilGUI#195]
hello guys i have a problem 

CONSOLE ERROR: `Plugin AstropolisBank v1.0 has failed to register events for class it.eccessivo.astropolisbank.atm.atmlistener because net/wesjd/anvilgui/AnvilGUI$Response does not exist.`

**Comment by WesJD** [comment]
You need to shade AnvilGUI into your project.
