### ISSUE TITLE
Deploy to latest version to codemc

### ISSUE THREAD

**Issue by SeanOMik** [WesJD/AnvilGUI#197]
The latest version of AnvilGUI is not deployed in the maven repository. It would bump to 1.5.4-SNAPSHOT. As far as I know, it only adds support for 1.18.2.

**Comment by Sytm** [comment]
As far as I know, the latest changes for 1.18.2 support are already in the Maven repository under the version 1.5.3-SNAPSHOT

**Comment by Chasewhip8** [comment]
@WesJD Can we please start bumping versions on this, the latest version in codemc does not have the 1.18.2 wrapper this is really annoying.

**Comment by Sytm** [comment]
But it does!
[This is the latest jar](https://repo.codemc.io/repository/maven-snapshots/net/wesjd/anvilgui/1.5.3-SNAPSHOT/anvilgui-1.5.3-20220302.153253-5.jar) at the moment for 1.5.3-SNAPSHOT.
If you look into it with an archive explorer you will find the wrappers for 1.18.2.

Maybe snapshot builds are just not refreshed by your build system. In my experience Gradle is very annoying in that regard.

**Comment by WesJD** [comment]
@Chasewhip8 as @Sytm has mentioned, the repository does contain the 1.18.2 changes. Please ensure to clear your local Maven cache.

**Comment by SeanOMik** [comment]
Why is the version not bumped though? Changes were made and a "new" version was released with support for 1.18.2. So why is AnvilGUI's version not bumped?
