### ISSUE TITLE
Bug on clicking on empty second slot

### ISSUE THREAD

**Issue by doppelkool** [WesJD/AnvilGUI#198]
**Steps to reproduce**:
- Version: 1.5.3-SNAPSHOT
- Modify Anvil Inventory in that way, that the second slot is empty.
- Open Anvil
- Rename Item to get option to complete
- Click on the empty slot

**Bugdescription**:
The "Enchantment Cost: **" are showing off again.

**Try to help**:
Maybe checking the item changes in the second slot on emptiness and cancel the packet to display the enchantment costs.

**Code**:
![image](https://user-images.githubusercontent.com/56027130/158907159-473a448f-237a-4b0e-a42b-4da8328ee321.png)

**Example video**:

https://user-images.githubusercontent.com/56027130/158907471-4372a524-6429-43bc-9e85-421b5c692769.mp4

**Comment by WesJD** [comment]
AnvilGUI has never made any effort to prevent the Enchantment Cost text from showing up at all. In the versions that this project started on, the Enchantment Cost text actually was always present. If it has not been showing for a while, that is a coincidence with some sort of Minecraft changes. If you would like to add this feature to the library, feel free to do so, but I will not be adding it personally.
