### ISSUE TITLE
Error while using CraftBukkit Remapped

### ISSUE THREAD

**Issue by GavinGoGaming** [WesJD/AnvilGUI#199]
Hey,
so I am using anvilGui in my project (1.18.2) and the "mvn clean install" wouldn't work so I just put the source code for anvil GUI in my project (pls tell me if I'm not allowed to do that, I gave full credit) and I tried to remake the Wrapper1_18_R2.java file but it seems there's an issue.

When I remade setActiveContainerDefault(Player) in nms remapped, I get the error below.

Code:
```java
    public void setActiveContainerDefault(Player player) {
        (toNMS(player)).containerMenu = (toNMS(player)).inventoryMenu;
    }
```
Error:
![image](https://user-images.githubusercontent.com/57292172/159170819-6cec3928-3c07-401b-bbd9-b8a4c5b9db03.png)

**Comment by Sytm** [comment]
> source code for anvil GUI in my project

I think that would be an unsupported use case. You should try to get maven working, because that what it is for: managing dependencies.

**Comment by GavinGoGaming** [comment]
Maven kept trying to compile 1.7-1.18.1 i only need 1.18.2. is there an arg I can use with "mvn clean install" to install ONLY 1.18.2?

**Comment by GavinGoGaming** [comment]
I tried to compile 1.18.2
using Java 16 {JDK-16}

[INFO] anvilgui-parent .................................... SUCCESS [  0.520 s]
[INFO] anvilgui-abstraction ............................... SUCCESS [  3.178 s]
[INFO] anvilgui-1_18_R2 ................................... FAILURE [  0.802 s]
[INFO] anvilgui ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.780 s
[INFO] Finished at: 2022-03-20T10:21:28-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project anvilgui-1_18_R2: Fatal error compiling: invalid target release: 17 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :anvilgui-1_18_R2

**Comment by Sytm** [comment]
Why bother doing that if you can just use the [precompiled jar](https://github.com/WesJD/AnvilGUI#as-a-dependency)?

The additional versions you don't need don't require that much space in your final jar

**Comment by GavinGoGaming** [comment]
Oh, thanks @Sytm!
For anyone else that doesnt use maven/gradle and just uses eclipse (or some other system) and has a section to add library .jar files, you can [download the jar file here](https://repo.codemc.io/repository/maven-snapshots/net/wesjd/anvilgui/1.5.3-SNAPSHOT/anvilgui-1.5.3-20220302.153253-5.jar) and add it to your build path.
