### ISSUE TITLE
Right Click Bug

### ISSUE THREAD

**Issue by portlek** [WesJD/AnvilGUI#20]
when im in the anvil gui then i click to output item with right mouse click, it comes to different page without anything
https://i.snag.gy/dbUT8p.jpg

not just right click, also drop(q)

**Comment by WesJD** [comment]
sorry for such a late response, but I am unable to replicate this issue. what is your server version?

**Comment by hsndmrts** [comment]
1.13.2

**Comment by WesJD** [comment]
Please reopen this issue if it is still occurring with source code provided and after extensive testing.
