### ISSUE TITLE
Could not resolve anvilgui

### ISSUE THREAD

**Issue by AoElite** [WesJD/AnvilGUI#202]
```gradle
repositories {
  maven {
        name = "codemc-snapshots"
        url = "https://repo.codemc.io/repository/maven-snapshots/"
    }
}

dependencies {
   implementation 'net.wesjd:anvilgui:1.5.3-SNAPSHOT'
}
```
![Image](https://cdn.upload.systems/uploads/nhDrmd7i.png)

I think there's a issue with the maven repository or something. This error just started happening with no changes to my build.gradle.

**Comment by WesJD** [comment]
The repository is online and working. This is an issue local to your machine.
