### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Feier68** [WesJD/AnvilGUI#205]
I'm not sure if I'm doing something wrong

version: 1.5.3-SNAPSHOT
mc version: 1.18.2
`[Builder_System_Plugin] Plugin Builder_System_Plugin v1.18.2.1.0.0 has failed to register events for class net.gigaclub.buildersystemplugin.Andere.Guis.Navigator because net/wesjd/anvilgui/AnvilGUI$Response does not exist.`

**Comment by Sytm** [comment]
Looks like you possibly have forgotten to shade AnvilGUI into your plugin

**Comment by Feier68** [comment]
do you mean dependency 
that is implemented


```
        maven {
            name = "codemc-snapshots"
            url = uri("https://repo.codemc.io/repository/maven-snapshots/")
        }
```
and     
  `compileOnly("net.wesjd:anvilgui:1.5.3-SNAPSHOT")`

**Comment by WesJD** [comment]
Closing this issue because @Sytm has answered the question.
