### ISSUE TITLE
Could not find the dependency

### ISSUE THREAD

**Issue by Jilence** [WesJD/AnvilGUI#208]
I have following problem: 

i am trying to add the dependency to my project. Everything worked fine 1-2 weeks ago, but now the following error message appears: "Could not find net.wesjd:anvilgui:1.5.3-SNAPSHOT.". Is there a new version..? Or why doesn't it work anymore

**Comment by MenschenToaster** [comment]
Having the same issue. Looking at the repository, I found out that the jar is missing for this version in the repo...

**Comment by Jilence** [comment]
so? Is there another possibility?

**Comment by Sytm** [comment]
[Everything is still where it's supposed to be](https://repo.codemc.io/#browse/browse:maven-snapshots:net%2Fwesjd%2Fanvilgui%2F1.5.3-SNAPSHOT%2F1.5.3-20220302.153253-5%2Fanvilgui-1.5.3-20220302.153253-5.jar)

**Comment by Feier68** [comment]
i have the problem too

**Comment by WesJD** [comment]
CodeMC is experiencing indexing issues with their repository right now. Hopefully the issue should be resolved soon. You can check the status on [their discord](https://discord.gg/A5w6VkJs).

**Comment by joestr** [comment]
I defined CodeMC as an upstream in my Archiva instance and it indeed seems that there is a problem with their repo.

**Comment by WesJD** [comment]
CodeMC has said that their repo has recovered, but people have mentioned that they are still having issues resolving a dependency with the latest version support. I just re-built manually on their CI and everything should be smooth sailing.
