### ISSUE TITLE
1.18.2 unsupported on latest snapshot

### ISSUE THREAD

**Issue by ThatGuyDavid09** [WesJD/AnvilGUI#209]
When this library is used in a plugin on a 1.18.2 server, it throws an error saying that 1.18.2 is an unsupported version. The latest snapshot, 1.5.3-SNAPSHOT, does not seem to include the 1.18.2 wrapper. Here is the relevant part of my pom.xml:

```xml
<repository>
        <id>codemc-snapshots</id>
        <url>https://repo.codemc.io/repository/maven-snapshots/</url> 
</repository>

<dependency>
        <groupId>net.wesjd</groupId>
        <artifactId>anvilgui</artifactId>
        <version>1.5.3-SNAPSHOT</version>
</dependency>
```

I tried to look through the maven repo to see if I was missing a snapshot, but I couldn't find anything.

**Comment by WesJD** [comment]
See #208. The maven repository is currently having issues.

**Comment by Sytm** [comment]
As it seems like that you actually were able to get a Jar from the Maven repository, it could also be that you have `<minimizeJar>true</minimizeJar>` in your Shade configuration, which must be turned off
