### ISSUE TITLE
Repository down

### ISSUE THREAD

**Issue by Chasewhip8** [WesJD/AnvilGUI#21]
https://nexus.wesjd.net/repository/thirdparty/

seems to be offline.

**Comment by WesJD** [comment]
looking into it. in the meantime, consider using jitpack.

**Comment by Chasewhip8** [comment]
I tried jitpack and added the dependency it said for the latest and it won't resolve for some reason, seems like its using the wrong URL format or something.

**Comment by WesJD** [comment]
should be something like
```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
	<dependency>
	    <groupId>com.github.WesJD</groupId>
	    <artifactId>AnvilGUI</artifactId>
	    <version>master-SNAPSHOT</version>
	</dependency>
```

**Comment by Chasewhip8** [comment]
[ERROR] Failed to execute goal on project CrashCore: Could not resolve dependencies for project net.craschraft:CrashCore:jar:3.0: Failure to find com.github.WesJD:AnvilGUI:jar:master-04a04e9b3b-1 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]

**Comment by Chasewhip8** [comment]
Doesn't seem to work.....hmmm

**Comment by Chasewhip8** [comment]
Using <version>master-04a04e9b3b-1</version> produces the same error

**Comment by Chasewhip8** [comment]
Still having issues resolving the artifact with jitpack... Is the main repo going to be back up?

**Comment by WesJD** [comment]
no, not soon. having major server issues.

**Comment by Chasewhip8** [comment]
@WesJD the build fails on jitpack due to the spigot jar requirements. The only reason i don't build it myself is that getting those jars locally is a pain in the ass and I could never get it to work.

**Comment by WesJD** [comment]
I am unable to provide you with an installable jar right now since I'm afk. if you're in desperate need, you need to install each version using build tools and then build the project. I can get a jar to you tomorrow night.

**Comment by Chasewhip8** [comment]
I finally got all the jars in my local repo so it's all good. Thanks for the api

**Comment by WesJD** [comment]
the repository is now back online.
