### ISSUE TITLE
Cannot reslove symbol 'minecraft' or what not

### ISSUE THREAD

**Issue by iXanadu13** [WesJD/AnvilGUI#214]
![image](https://user-images.githubusercontent.com/104714710/166149819-310df9d2-4e2b-402b-b017-1962c14baafa.png)

**Comment by joestr** [comment]
What are you trying to achieve here? You don't have to copy the AnvilGUI source to your plugins source directory.

**Comment by joestr** [comment]
I responded in now closed issue #213.

**Comment by iXanadu13** [comment]
I just want to use the anvilgui function.I have tried not to copy the AnvilGUI source,but always failed.

My previous problem: https://github.com/WesJD/AnvilGUI/issues/213
