### ISSUE TITLE
Github Actions having trouble Downloading from CodeMC

### ISSUE THREAD

**Issue by GamerCoder215** [WesJD/AnvilGUI#215]
Hello,
I'm trying to use GitHub Actions to build my project (with this as a dependency), and it seems to have some issues trying to download it:

![image](https://user-images.githubusercontent.com/54124162/171482936-bb70cb95-62d0-46c7-a691-eb2e94886ade.png)

This has been going on quite a while (and is very inconsistent), so it may require a few tries if you're going to try to reproduce it.

**Comment by zax71** [comment]
[I'm getting this issue too] (https://github.com/zax71/EndercubePlugin/runs/6713761072)

**Comment by WesJD** [comment]
I do not run the CodeMC repo. Please seek support on [their discord](https://discord.gg/MRtGVqwy).
