### ISSUE TITLE
Need to Compile against Java 1.8

### ISSUE THREAD

**Issue by GamerCoder215** [WesJD/AnvilGUI#217]
Hello,
I need to compile against Java 1.8 (for MC 1.8 support), but maven is throwing a fit since your 1.17 and 1.18 wrapper classes compile in Java 16 and 17:
![image](https://user-images.githubusercontent.com/54124162/172523370-7bf23fe3-198c-4c0e-8bb3-c7c6cff0b1bd.png)

Would it be possible for you to migrate your wrappers to Java 8?

**Comment by joestr** [comment]
You can try to exclude the wrappers which cause troubles.

**Comment by GamerCoder215** [comment]
> You can try to exclude the wrappers which cause troubles.
> Just use a older version of AnvilGUI instead that does not include the wrappers for newer Minecraft versions. The wrappers for older Minecraft versions have not changed anyway. The newer versions require JDK 16/17 because Minecraft classes use those class versions.
I still want support for those versions... is there a solution for that?

**Comment by Sytm** [comment]
You use the incorrect version of Maven Shade. The correct version can be found in the README of this project

**Comment by GamerCoder215** [comment]
> You use the incorrect version of Maven Shade. The correct version can be found in the README of this project

Thanks! This worked :)
