### ISSUE TITLE
Suggestion for "minimizeJar"

### ISSUE THREAD

**Issue by mfnalex** [WesJD/AnvilGUI#224]
Hi, nice library!

I noticed that you tell people to not use "minimizeJar" because it obviously doesn't detect classes used through reflection.

For my JeffLib library, I simply tell people to add a filter to the shade plugin, maybe you can also add this to your README if you like. I'd normally pull request it but I'm quite busy rn. Something like this will include the required classes even when using minimizeJar:

```xml
            <filter>
                <artifact>*:*</artifact>
                <excludeDefaults>false</excludeDefaults>
                <includes>
                    <include>com/jeff_media/jefflib/internal/nms/**</include>
                </includes>
            </filter>
```

Have a nice day!

**Comment by mfnalex** [comment]
It also works when you're relocating classes btw

**Comment by ipiepiepie** [comment]
+1

Current README can confuse some inexperienced developers.

Also, in Gradle you can use something like that:
```Gradle
shadowJar {
    minimize() {
        exclude(dependency('net.wesjd:anvilgui:.*'))
    }
}
```
