### ISSUE TITLE
Version 3.3.0

### ISSUE THREAD

**Issue by PhilCode-creator** [WesJD/AnvilGUI#225]
Hey,
Im trying to use your API, but maven says version 3.3.0 is not existing
Im using spigot 1.8.8 (Java 8)
![image](https://user-images.githubusercontent.com/55019948/181917584-52dc75fb-0c38-4a8e-b0d1-eafe680a3c0a.png)

Cheers

**Comment by joestr** [comment]
Did you start a build? If not, start a build then Maven will download the missing plugin.

**Comment by PhilCode-creator** [comment]
Works Thank you so much
