### ISSUE TITLE
Click action per slot

### ISSUE THREAD

**Issue by BONNe** [WesJD/AnvilGUI#23]
Currently, it is possible to register only click action on the ouput slot, but there are still 2 slots that could be useful in some situations.

F.e. I have a panel GUI that opens AnvilGUI, but the only way how to get back is by changing a name or clicking outside GUI. 
It would be useful to have the ability to define one more button, like a 2nd input slot, that could return to a previous GUI.

Adding the ability to define actions per each slot click would allow more variation.

**Comment by WesJD** [comment]
The first slot needs to be something simply to rename, and the second cannot be filled with anything except for the first or else it wouldn't be able to produce a result

**Comment by BONNe** [comment]
So, the request was about ability to provide Consumer actions for all slots.

Yes, output slot that returns a value still will be last slot, but adding option, that allows detecting clicks on other slots, even if they do not return anything, could be useful.

F.e.
Creating consumer, that resets original value, if player clicks on first item.
Creating consumer, that exit AnvilGUI, if player clicks on second item.

**Comment by WesJD** [comment]
Absolutely feel free to create a PR with this and I'll consider it. I won't be adding it myself, however.
