### ISSUE TITLE
AnvilGUI$Response does not exist

### ISSUE THREAD

**Issue by Eccessiv0** [WesJD/AnvilGUI#230]
[AziendeWC] Plugin AziendeWineCity v1.0.0 has failed to register events for class it.eccessivo.aziende.ATM.ATMListener because net/wesjd/anvilgui/AnvilGUI$Response does not exist.

**MY CODE:**
![code](https://user-images.githubusercontent.com/94767454/190469045-221787f4-51ee-44fb-9509-65dbd27fb8fe.png)

**MY POM.XML**
![pom](https://user-images.githubusercontent.com/94767454/190469561-3536797b-0e4c-4094-a419-db7712260ccd.png)

pls help

**Comment by WesJD** [comment]
You need to shade the dependency.
