### ISSUE TITLE
Plugin McConsept v1.0-SNAPSHOT has failed to register events for class disprodev.main.listeners.InventoryListener because net/wesjd/anvilgui/AnvilGUI$Response does not exist.

### ISSUE THREAD

**Issue by DisPro** [WesJD/AnvilGUI#236]
pom.xml 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>disprodev</groupId>
    <artifactId>main</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>McConsept</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>net.wesjd.anvilgui</pattern>
                                    <shadedPattern>MineConcept</shadedPattern> 
                                </relocation>
                            </relocations>
                            <minimizeJar>false</minimizeJar> 
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
            <repository>
                <id>jitpack.io</id>
                <url>https://jitpack.io</url>
    </repository>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.5.3-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.19.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>
</project>

**Comment by portlek** [comment]
which command do you use for building your plugin jar file?

**Comment by DisPro** [comment]
I use the artifacts build from intellj

**Comment by DisPro** [comment]
I have a problem when compiling lambda expressions are not supported in -source 1.7 if you know how to fix it 

> Try to build your plugin with Maven ![within Intellij](https://camo.githubusercontent.com/97c3eb84b59a0d958035067355d5c3929b8b597585fce4ab93fd886ce02cf5e0/68747470733a2f2f7777772e6a6574627261696e732e636f6d2f68656c702f696465612f6275696c642d6f766572766965772e68746d6c236d6176656e5f6275696c64).
