### ISSUE TITLE
Do something after return Response to close

### ISSUE THREAD

**Issue by Fokpi** [WesJD/AnvilGUI#238]
A way to do something after Response.close because when i kick my player before it does a packet error, or when i want to open a gui with Triumph Api i cant use open inventory because my gui work with functions and i call function to open gui so if it's possible a way to execute actions after closing inventory

**Comment by WesJD** [comment]
We could definitely implement a `AnvilGUI.Response.closeThenRun(() -> { /* your code here */})`
