### ISSUE TITLE
InventoryClickEvent error

### ISSUE THREAD

**Issue by PhantomClone** [WesJD/AnvilGUI#244]
In the private class ListenUp

You try to compare a nullable Inventory with a Player.

 Player clicker = (Player)event.getWhoClicked();
 if (event.getClickedInventory().equals(clicker) && event.getClick().equals(ClickType.DOUBLE_CLICK)) {
 
So, if you click outside the anvil gui -> and event.getClickedInventory() is null, we get a NullPointerException Cannot invoke "Object.equals(Object)"

**Comment by WesJD** [comment]
Good catch. Fixed!
