### ISSUE TITLE
A target for anvil's inventory?

### ISSUE THREAD

**Issue by zS0bye** [WesJD/AnvilGUI#246]
Would it be possible to add a target for the anvil inventory? type x.getInventory(), maybe even in the onClose() event. Or add on onClose() the target of the left and right item. Thank you very much!

**Comment by WesJD** [comment]
Could you describe more in-depth what you are looking for? I don't understand from your description.

**Comment by zS0bye** [comment]
> Could you describe more in-depth what you are looking for? I don't understand from your description.

In the AnvilGUI builder, I was wondering if it was possible to put that onClose(Consumer<Player>)

 it was possible to put a target of the left and right item.  Because I need that when one closes the inventory, if he leaves the items in those 2 slots, they either come back to you or throw them on the ground.

**Comment by WesJD** [comment]
Yeah, makes sense. We could definitely provide something like the `Completion` to onClose. Marking as help wanted.
