### ISSUE TITLE
How do i build against a specific commit?

### ISSUE THREAD

**Issue by TheSilentPro** [WesJD/AnvilGUI#258]
When updating versions i noticed you don't push the changes to a new patch version. 
Since it's from codemc how am i supposed to build against the latest commit instead of a specific version?

**Comment by Sytm** [comment]
At the moment the latest available version is [1.6.3-SNAPSHOT](https://repo.codemc.io/#browse/browse:maven-public:net%2Fwesjd%2Fanvilgui%2F1.6.3-SNAPSHOT), but it has been rereleased 3 addtional times now with the latest changes. Maybe take a look at this SO answer: https://stackoverflow.com/a/5901460
