### ISSUE TITLE
Is there a way to get text in onClose listener?

### ISSUE THREAD

**Issue by misteeka** [WesJD/AnvilGUI#259]
I want to save changes not only onComplete, but onClose as well. Is it possible?

**Comment by misteeka** [comment]
While I wait developers answer... if someone will encounter this problem I actually found a creepy (but simple) way to make this work
`final var instance = new AtomicReference<>(null);
            final var builder = new AnvilGUI.Builder()
                    .onClose(player -> {
                        if(inventory.get() == null) return;
                        var result = inventory.get().getInventory().getItem(2);
                        if(result == null) return;
                        var text = result.getItemMeta().displayName();
                    })
                    .plugin(plugin);
            instance.set(builder.open(player));`

**Comment by WesJD** [comment]
I predicted a request for this to occur very soon. Check our #253. Hopefully can merge soon.

**Comment by WesJD** [comment]
Feature added in #253
