### ISSUE TITLE
NullPointerException when using ResponseAction.replaceInputText()

### ISSUE THREAD

**Issue by Sytm** [WesJD/AnvilGUI#262]
With the addition of the StateSnapshot and generic click handler, the [null check](https://github.com/WesJD/AnvilGUI/blob/5e8eac0ad89a9fc07dc1eb2cdd03469121cae408/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L245) on the clicked item has been removed and now if a player would click into the empty output slot because he has not yet changed the text and the ClickHandler would return ResponseAction.replaceInputText(), a NullPointerException would be thrown because it [tries to clone](https://github.com/WesJD/AnvilGUI/blob/1586ce6fe0efcec514429d37fdc795d923505df1/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L464) the contents of the output slot.

Why is the current behavior that the output is cloned and renamed and then put into the input instead of just renaming the input in place?

**Comment by WesJD** [comment]
Good find. I suppose we should make `replaceInputText` rename the `INPUT_LEFT` slot if the `OUTPUT` slot is empty. Is this the most logical solution?

> Why is the current behavior that the output is cloned and renamed and then put into the input instead of just renaming the input in place?

I believe I had done this in the eye of the user of the API not having things changed out from under them if possible. It ensures that the changes the library makes to the GUI are isolated and don't have unintended effects in the developer's code.
