### ISSUE TITLE
Custom #itemOutput

### ISSUE THREAD

**Issue by Satellq** [WesJD/AnvilGUI#266]
Hello, I'm trying to make the output item different from the left item but when I do something like this:
```
.itemLeft(generateItemUI(Material.DIAMOND_HOE, (short) 24))
.itemOutput(generateItemUI(Material.WOOD_HOE, (short) 3))
```
the output becomes the wood hoe for a frame and then sticks with the diamond hoe.

I'm using the lastest AnvilGUI version with Minecraft 1.12

**Comment by WesJD** [comment]
Please provide some screenshots. Regardless, this sounds like #237, which is a limitation of the inventory on Minecraft's side that has been discussed but not implemented in permitting.

**Comment by Satellq** [comment]
https://imgur.com/a/Z4Faibg

So there is no way you can do it? I saw a 1.12.2 server have this thing but from the left item and the output, the only difference was the metadata and not the material.

**Comment by WesJD** [comment]
Please provide a minimally reproducible example and describe what is happening. I can't really understand what is going on in the video.
