### ISSUE TITLE
Using hex colours in anvil title

### ISSUE THREAD

**Issue by UwUAroze** [WesJD/AnvilGUI#269]
Maybe I'm missing something but I can't seem to find a way to use hex colour codes in the anvil's title without it converting to legacy colours

**Comment by Sytm** [comment]
You could try to parse the string into bungeecord-chat TextComponents and then serialize them into Json and pass them as the title argument.

No guarantee that it is going to work. If not it would require changes to AnvilGUI to make it work.

**Comment by WesJD** [comment]
Yeah, there isn't a way to do this. It's unfortunately a much harder problem than you would initially think because we need to continue supporting versions as old as 1.8. Check out #233 for more context.

**Comment by UwUAroze** [comment]
😔that's okay. I saw you briefly mentioned the possibility of implementing version-specific logic, are there still plans for that? Alsoo, couldn't hex be supported alone without the use of Adventure and MiniMessage, eliminating some of those other issues?
