### ISSUE TITLE
The problem is that text input does not work on most pirated launchers. Summary text is empty

### ISSUE THREAD

**Issue by Lisenochek** [WesJD/AnvilGUI#273]
The problem is that text input does not work on most pirated launchers. Summary text is empty

```
 new AnvilGUI.Builder()
                .plugin(Main.getPlugin())
                .itemLeft(Icons.INVISIBLE_ICON.create(name))
                .allowConcurrentClickHandlerExecution()
                .onClickAsync((slot, stateSnapshot) -> CompletableFuture.supplyAsync(() -> {
                    player.playSound(player.getLocation(), Sound.UI_BUTTON_CLICK, 1, 1);

                    if (slot == AnvilGUI.Slot.INPUT_LEFT)
                        return Collections.singletonList(AnvilGUI.ResponseAction.run(() -> mainGUI(playerData)));

                    if (slot != AnvilGUI.Slot.OUTPUT) return Collections.emptyList();

                    return Collections.singletonList(AnvilGUI.ResponseAction.run(() -> {
                        this.name = stateSnapshot.getText().isBlank() ? name : stateSnapshot.getText();
                        player.closeInventory();
                        player.sendActionBar(Utils.replaceColors(LocalePaths.INSTANCE.MESSAGES_ACTION_BAR_RESPAWN_POINT_RENAME.getString()));
                    }));
                }))
                .open(player);
```

**Comment by Lisenochek** [comment]
demo https://www.youtube.com/watch?v=-6pfsTTN7BY&ab_channel=helicopteris

**Comment by WesJD** [comment]
Please provide a minimally reproducible example of your problem.

**Comment by Lisenochek** [comment]
You must use your api, and use some unlicenced launcher (ex. TLauncher)

**Comment by WesJD** [comment]
This project does not make distinctions about launchers. If you can't provide a minimally reproducible example of your problem, then there is nothing to be fixed.

**Comment by Lisenochek** [comment]
I'm telling you. The problem is not reproduced from licensed game launchers. On my server, there is an opportunity to log in from both pirated launchers and licensed ones, and the vast majority of players use the first option

**Comment by Sytm** [comment]
I attempted to replicate this issue on an offline Spigot and Paper server version 1.20.1 with an Vanilla client on 1.20.1 also launched in offline-mode and everything worked without any flaws. There seems to be no issue even in offline-mode
