### ISSUE TITLE
Item changing automatically 

### ISSUE THREAD

**Issue by ViiictorXD** [WesJD/AnvilGUI#286]
When I open the Anvil GUI, the **leftItem** and **outputItem** is changing automatically, follow my code:
![image](https://github.com/WesJD/AnvilGUI/assets/38568440/0f060630-a849-4633-b8a1-f7613a767adf)

Follow what happen (video):
https://github.com/WesJD/AnvilGUI/assets/38568440/01716eb0-6f20-42b9-b7de-2bf9219a868a

**Comment by Sytm** [comment]
Well, from `itemLeft` the AnvilGUI takes its starting text. You calling `.text` on the Builder overwrites the Displayname "Back". The only reliable item that can keep its DisplayName is itemRight, otherwise you need to move the "Back" text into the lore aswell
