### ISSUE TITLE
[Question] What is the plugin field used for?

### ISSUE THREAD

**Issue by nopeless** [WesJD/AnvilGUI#288]
There's not much documentation about it. I have read the source as well, and there isn't much either. Where is this used for?

Thanks in advance

**Comment by joestr** [comment]
What field are you refering to?

**Comment by nopeless** [comment]
`Builder#(Plugin plugin)`

**Comment by Sytm** [comment]
It is used to register the event handlers and to schedule the task when preventClose is used
