### ISSUE TITLE
Anvil gui takes XP when the result slot is clicked

### ISSUE THREAD

**Issue by Trophonix** [WesJD/AnvilGUI#29]
Tested in version 1.14. It takes the XP cost listed on the GUI when you click.

**Comment by Trophonix** [comment]
I would submit a PR, but I don't know why it's happening. Would need to dive deeper into the NMS of it, which is why I avoided making my own in the first place haha. If it helps, the anvil succeeds even when player has 0 XP. But if you have positive XP it subtracts.

**Comment by WesJD** [comment]
I'll see if I can take a look tomorrow.

@tchristofferson any insight?

**Comment by Trophonix** [comment]
I would love to be able to use this lib in a plugin of mine, actually a couple of them. It's full featured and everything works nicely, unlike the other couple libs I found where I had huge problems.

May try to work on the issue tomorrow if I end up with some free time. I'll submit a PR if I manage a fix.

**Comment by WesJD** [comment]
@Trophonix Thanks for any effort put forth. I apologize for being unable to update it thus far, I've just been super tight on time. As a result, I'm in search of a new maintainer too.

**Comment by Trophonix** [comment]
Yeah I saw your post on spigot. No worries, I understand. Your efforts in
maintaining it this far and looking for a new maintainer now are admirable!

I got distracted doing some work on another plugin but when I get back to
the project I'm using this in I do plan to work on it. I will take on the
maintainence of anvilgui if that suits you.

@Trophonix <https://github.com/Trophonix> Thanks for any effort put forth.
> I apologize for being unable to update it thus far, I've just been super
> tight on time. As a result, I'm in search of a new maintainer too
>

**Comment by tchristofferson** [comment]
This might work if I set the damage of the paper itemstack, in the left box of the anvil, to 0. I will have to test it later and see.

**Comment by WesJD** [comment]
@tchristofferson the version implementations i wrote for 1.8-1.13 [did override the method that prevented the anvil from requiring experience levels](https://github.com/WesJD/AnvilGUI/blob/master/1_8_R3/src/main/java/net/wesjd/anvilgui/version/Wrapper1_8_R3.java#L107).

**Comment by tchristofferson** [comment]
Committed fix.
