### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by vortexthedev** [WesJD/AnvilGUI#297]
Doesn`t work at all for me using 1.19.4, 1.20.1, 1.20.2 versions.
My code:

```
        new AnvilGUI.Builder().
                onClick((slot, state) -> {
                    if(slot != AnvilGUI.Slot.OUTPUT)
                        return Collections.emptyList();

                    return List.of(
                            AnvilGUI.ResponseAction.run(() -> player.performCommand("friend add " + state.getText()),
                            AnvilGUI.ResponseAction.close()
                    );
                }).
                title(ChatColor.GREEN + "Enter username").
                text("User").
                plugin(plugin).
                open(player);
```

**Comment by vortexthedev** [comment]
https://gyazo.com/e0a95ad4b19a79edb322ea07011ad94f

**Comment by mastercake10** [comment]
I was not able to reproduce your issue.

A few thoughts:
1. Your List of ResponseAction is invalid, you are missing a `)`:
`AnvilGUI.ResponseAction.run(() -> player.performCommand("friend add " + state.getText()),` -> `AnvilGUI.ResponseAction.run(() -> player.performCommand("friend add " + state.getText())),`, so it won't compile. Even with this fix your code works as expected.
2. Where does `player` come from? You should use `state.getPlayer()` here.
3. Your recording shows a GUI with a nether star and some foreign characters, so your code differs from the recording. Maybe this is relevant to resolve your issue.

Please provide the full source code to look into this further

**Comment by vortexthedev** [comment]
`    public void action(Player player, String text, String command) {
        player.closeInventory();
        new AnvilGUI.Builder().
                onClick((slot, state) -> {
                    if(slot != AnvilGUI.Slot.OUTPUT)
                        return Collections.emptyList();

                    return List.of(
                            AnvilGUI.ResponseAction.run(() -> player.performCommand(command + " " + state.getText())),
                            AnvilGUI.ResponseAction.close()
                    );
                }).
                itemLeft(new ItemStack(Material.NETHER_STAR)).
                title(ChatColor.GREEN + "Enter " + text).
                text("Answer").
                plugin(YourPlugin.getInstance()).
                open(player);
    }`

**Comment by WesJD** [comment]
Have you tried this with only anvilgui running on the server? Looks like a classic conflicting plugin.

**Comment by vortexthedev** [comment]
![image](https://github.com/WesJD/AnvilGUI/assets/72511773/94e3c738-059a-41bd-9938-d4a5739055da)

**Comment by WesJD** [comment]
So no, you didn't do that? You sent a picture with 15 plugins loaded.

**Comment by vortexthedev** [comment]
Add me to Discord please: @vortex2252
