### ISSUE TITLE
1.14.2 issue

### ISSUE THREAD

**Issue by nkomarn** [WesJD/AnvilGUI#30]
Hey, so I use AnvilGUI in a custom plugin of mine. When I try to use the GUI in 1.14.2, it results in this error:
![image](https://user-images.githubusercontent.com/22900187/59705194-bea1ed00-91b2-11e9-9cd0-bb4810ea5489.png)
It works fine in 1.13.2, just not on my 1.14.2 server. Hope you can do something about this!

**Comment by tchristofferson** [comment]
I can take a look at this later today. I think it is a simple fix, but we will see.

**Comment by tchristofferson** [comment]
What version of Java do you have just out of curiosity?

**Comment by tchristofferson** [comment]
What version of Java are you running?

**Comment by nkomarn** [comment]
> What version of Java are you running?

I'm running Java 11.

**Comment by tchristofferson** [comment]
Can you share the code you used to get this error?

**Comment by nkomarn** [comment]
That happened with the default example code you provided.

**Comment by nkomarn** [comment]
![image](https://user-images.githubusercontent.com/22900187/60199578-1a92f400-97f9-11e9-9789-9cdf3cab134d.png)
Also, I ran into this issue if you want to give a crack at fixing it. I think you just need to replace
`player.closeInventory()` with `if (player.getOpenInventory() != null) player.closeInventory();`

**Comment by Speentie8081** [comment]
player.getOpenInventory() never returns null. I'm looking into this issue right now.

**Comment by Speentie8081** [comment]
> Hey, so I use AnvilGUI in a custom plugin of mine. When I try to use the GUI in 1.14.2, it results in this error:
> ![image](https://user-images.githubusercontent.com/22900187/59705194-bea1ed00-91b2-11e9-9cd0-bb4810ea5489.png)
> It works fine in 1.13.2, just not on my 1.14.2 server. Hope you can do something about this!

Please test now using the latest fixes.

**Comment by Speentie8081** [comment]
You can use [jitpack.io](https://jitpack.io/#WesJD/AnvilGUI) for bleeding edge updates.

**Comment by tchristofferson** [comment]
@nkomarn Should be fixed after latest commits.

**Comment by WesJD** [comment]
60a74d2 possibly reopens this issue.

**Comment by nkomarn** [comment]
Can confirm that the issue still occurs.

**Comment by WesJD** [comment]
Was this fixed in 5e3ab1f?

**Comment by BONNe** [comment]
It looks like with openJDK 12 you cannot change private final variables with changing "modifiers".
At least, it is not working for me with 1.14.4

**Comment by nkomarn** [comment]
I have narrowed it down to a Java issue - I downgraded my JRE to 1.8 on my server and it's perfect now. This needs to be resolved.

**Comment by TychoVI** [comment]
Also happens in the latest version for 1.14.4 with java 11 fyi.

**Comment by portlek** [comment]
https://stackoverflow.com/a/56043252

**Comment by WMGameLive** [comment]
Still happens in the latest version for 1.14.4 with java 11

**Comment by portlek** [comment]
I'll try something about changing final fields.

**Comment by portlek** [comment]
Sorry but no way to do that without editing the server jar.

**Comment by portlek** [comment]
```java
public final class Test {

    private static final VarHandle MODIFIERS;

    static {
        try {
            final var lookup = MethodHandles.privateLookupIn(Field.class, MethodHandles.lookup());
            MODIFIERS = lookup.findVarHandle(Field.class, "modifiers", int.class);
        } catch (IllegalAccessException | NoSuchFieldException ex) {
            throw new RuntimeException(ex);
        }
    }

    public void start() throws Exception {
        final var newWindowId = 15;
        final var field = FinalTest.class.getDeclaredField("windowId");

        makeNonFinal(field);
        field.setAccessible(true);
        field.set(null, newWindowId);

        System.out.println(FinalTest.getWindowId());
    }

    private void makeNonFinal(Field field) {
        final int mods = field.getModifiers();

        if (Modifier.isFinal(mods)) {
            MODIFIERS.set(field, mods & ~Modifier.FINAL);
        }
    }

    public static void main(String[] args) {
        try {
            new Test().start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
```
I tried something like that.

**Comment by BONNe** [comment]
You cannot do it anymore in Java. 
You can still try to get java-8 and use it as your server runner. Then it will work.

**Comment by portlek** [comment]
So, It's not AnvilGUI bug. This issue can be closed @WesJD

**Comment by BONNe** [comment]
It kinda is. 
You cannot use anvilGUI with new java.

**Comment by WesJD** [comment]
100% possible to fix by extending Container and making our own containerId field (and then implementing it in all methods). However, I just don't have the time right now to work on it.

**Comment by WesJD** [comment]
Glad to have this fixed.
