### ISSUE TITLE
Output display name item is being set to rename text

### ISSUE THREAD

**Issue by MarekOS2** [WesJD/AnvilGUI#303]
Even if I change the name by doing:
`anvilGui.itemOutput(confirmNameItem);`
it is being set to whatever is being written in the text field, so basically this line of code does nothing

also the text cannot be set to empty string 
` anvilGui.text("")` because the text gets taken from the display name of items.
For example when I have the left item display name as `"example"` and the text is `""` or just not set, the text will be set as `"example"`

**Comment by WesJD** [comment]
It seems you think you are required to call the `text` method of the builder. You aren't. 

The `text` method will override the name of your `itemOutput` by design. If you want to use the name of `itemOutput`, just don't call `text`.
