### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by FaMa91** [WesJD/AnvilGUI#312]
I cannot manage to resolve the NoClassDefFoundError:

The error:
![immagine](https://github.com/WesJD/AnvilGUI/assets/13115141/58a1ded2-5490-4606-96c0-22ab628e192e)

The method:

	private void search() {

		new AnvilGUI.Builder()
				.onClose(stateSnapshot -> {
					stateSnapshot.getPlayer().sendMessage("You closed the inventory.");
				})
				.onClick((slot, stateSnapshot) -> { // Either use sync or async variant, not both
					if(slot != AnvilGUI.Slot.OUTPUT) {
						return Collections.emptyList();
					}

					if(stateSnapshot.getText().equalsIgnoreCase("you")) {
						stateSnapshot.getPlayer().sendMessage("You have magical powers!");
						return List.of(AnvilGUI.ResponseAction.close());
					} else {
						return List.of(AnvilGUI.ResponseAction.replaceInputText("Try again"));
					}
				})
				.preventClose()
				.text("What is the meaning of life?")
				.title("Enter your answer.")
				.plugin(Feudal.getPlugin());
	}

The pom: https://pastebin.com/vVPdJaSX

**Comment by joestr** [comment]
Which `.jar` did you put into the plugin folder? It seems like you did not deploy the `*-shaded.jar` file.

The `pom.xml` looks fine at the first glance.

**Comment by FaMa91** [comment]
I used the *-shaded.jar

@WesJD Why this issue has been closed?

**Comment by WesJD** [comment]
> @WesJD Why this issue has been closed?

Because this is not a problem with AnvilGUI.

**Comment by FaMa91** [comment]
How can you tell it? Do you know what is wrong and choose to not tell me or you are just assuming It?
Anyway, yes it is, I managed to solve it myself. Your readme is wrong.

You as a developer should help people with this kind of problems too, I know is frustrating but is part of the job.
