### ISSUE TITLE
How to implement AnvilGUI?

### ISSUE THREAD

**Issue by Ghoooosty** [WesJD/AnvilGUI#318]
Hey,
i implemented everything i need in the pom.xml file, also was able to call methods of AnvilGUI in my own Plugin. But after starting the Server, and executing the command, an error called ,,Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder". Do i need to get any type of jar file for the plugin folder, or for my own Plugin?
Thanks in advance

**Comment by mastercake10** [comment]
Make sure that your final .jar-File actually includes the files from AnvilGUI (open it as an archive). If its not in there, you have used the wrong build command (use `mvn package`, you can select "package" from your IDE) or you made a mistake in your pom file. Post your pom file if it still doesn't work.

**Comment by Ghoooosty** [comment]
[pom.txt](https://github.com/WesJD/AnvilGUI/files/14669396/pom.txt)
here you go... mvn package didn´t work for me... Thanks for your help! I won´t say, that i didn´t do any faults in my "pom.xml"... In that pom.txt i just excluded my groupID etc., the rest is still there

**Comment by mastercake10** [comment]
You are using the wrong scope for the AnvilGUI dependency:
```xml
(...)
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.9.2-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
(...)
```
the scope should be _compile_, which is the default scope. So just remove the scope line.
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope
