### ISSUE TITLE
Is the version matcher broken?

### ISSUE THREAD

**Issue by titanbornMunky** [WesJD/AnvilGUI#321]
I thought i had read something from bukkit saying you should not do any string manipulation to get the server version / nms version, and to only use dedicated methods. i bring this up because of this

![image](https://github.com/WesJD/AnvilGUI/assets/162915860/b0533d33-23e3-4c76-886d-06fa674ee293)

![image](https://github.com/WesJD/AnvilGUI/assets/162915860/85499d8f-8e8c-40fc-ac2f-de5e9e05c526)

![image](https://github.com/WesJD/AnvilGUI/assets/162915860/d26c470f-cb5f-4c15-95c7-9760b0243533)

I am shading it into my plugin

**Comment by WesJD** [comment]
Based on the error message, I don't think this is related to #294. It looks like the version is being parsed correctly, but it can't find the version for that package. Have you decompiled your jar and made sure the version exists in your jar?
