### ISSUE TITLE
Move to gradle.

### ISSUE THREAD

**Issue by portlek** [WesJD/AnvilGUI#325]
This will make our life easier when implementing #302
maven is relatively hard to add kotlin support, so it would be much more easier to make it in a Gradle environment.

**Comment by 0dinD** [comment]
I don't see how this is related to #302 (which just seems to be a documentation issue), but maybe I have misunderstood what #302 is about?

> maven is relatively hard to add kotlin support,

Kotlin support *for what*? You can already use Gradle with Kotlin to depend on AnvilGUI.

**Comment by portlek** [comment]
> Kotlin support _for what_? You can already use Gradle with Kotlin to depend on AnvilGUI.

im not talking about that. i was talking about the #302 to make it easier to implement.

**Comment by 0dinD** [comment]
Yeah I had just misunderstood what #302 was about, your argument makes sense now. It seems doable to [build Kotlin code with Maven](https://kotlinlang.org/docs/maven.html), but I would also not be surprised if Jetbrains has given the Gradle plugins for Kotlin more love than the Maven counterparts, so I trust your experience if you say that it's much easier in Gradle (I have not used Kotlin much, so I wouldn't know).

**Comment by 0dinD** [comment]
Moving to Gradle seems like an implementation detail to me, for someone who uses AnvilGUI it won't matter whether we use Maven or Gradle. The simplicity of Maven is very appealing, so unless we have a strong reason to move to Gradle, I don't think it makes sense to switch. That matter can be discussed if and when such a reason comes along.
