### ISSUE TITLE
Cannot depend on latest version on Java 8

### ISSUE THREAD

**Issue by PikaMug** [WesJD/AnvilGUI#329]
README states Java 8 is supported under Requirements. A maven project I manage compiles using 1.9.3-SNAPSHOT just fine, but 1.9.4-SNAPSHOT returns the same "Unsupported class file major version 65" as #328 

I decided to compile AnvilGUI locally (with Java 21 as the runner) and the resulting jar works fine as a dependency using `<systemPath>` scope. Has there maybe been some change to CodeMC that's causing this issue?

_Side note: Seems like [.mvn/jvm.config](https://github.com/WesJD/AnvilGUI/blob/master/.mvn/jvm.config) may no longer be necessary with the new version of spotless._

**Comment by PikaMug** [comment]
Decided to send it to Jenkins, same result. Log: https://ci.codemc.io/job/PikaMug/job/MilkGUI/51/console

**Comment by mastercake10** [comment]
The `maven-shade-plugin` version in your plugin needs to be at least `3.5.0`, i.e.
```xml
         <plugins>
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-shade-plugin</artifactId>
                 <version>3.5.3</version>
                 (...)
 ```
let me know if this fixes the issue, we need to update the readme then

**Comment by PikaMug** [comment]
@mastercake10 Thank you, that did the trick! I'll leave this open until one of us PRs the readme.

**Comment by WesJD** [comment]
updated readme
