### ISSUE TITLE
Not compatible with version 1.20.4

### ISSUE THREAD

**Issue by EURedBoy** [WesJD/AnvilGUI#341]
![image](https://github.com/user-attachments/assets/d0322358-5588-47a1-aeb5-9eeb089c4a73)
![image](https://github.com/user-attachments/assets/ec5ef003-df2b-4654-8c0c-f8fac91ed573)

If i open the library i can see the wrapper, so i don't know why he can't find it
![image](https://github.com/user-attachments/assets/6c32775a-0255-4863-92c3-54732d9344e8)

**Comment by StarlessDev** [comment]
I actually encountered the same problem 10 minutes ago.
On my end It was a shading issue: the jar was minimized and the wrappers were removed. When not minimizing the jar everything works. Maybe you have the same issue?

**Comment by joestr** [comment]
If the filter section is like the one in the README.md file the `<minimizeJar>` option has no effect on that.

@EURedBoy can you share the affecting portion of  your `pom.xml` file?

**Comment by EURedBoy** [comment]
> If the filter section is like the one in the README.md file the `<minimizeJar>` option has no effect on that.
> 
> @EURedBoy can you share the affecting portion of your `pom.xml` file?

Sorry if i'm late, i fixed while ago simply excluding the anvilgui package from the minimize action
![image](https://github.com/user-attachments/assets/ba7ed22d-3199-4a6f-a964-d89b5291306e)
(i use gradle not maven)
