### ISSUE TITLE
OnClose listener option?

### ISSUE THREAD

**Issue by Trophonix** [WesJD/AnvilGUI#35]
It would be really useful if I had a way to catch when the inventory was closed. I'm trying to use this for a GUI-based plugin and I need to open back up my GUI when the anvil is closed regardless of whether they gave input. Tried a quick solution by making my own class that extends AnvilGUI with its own listener but that don't work haha.

For now I will just make the class I'm using it in a Listener and make my own onClose method but it'd be a nice feature!

Implementation ideas:
- Add a Consumer\<Player\> arg to the constructor (or add a new constructor with that on the end)
- Add a .onClose(Consumer\<Player\>) method (could sort of turn it into a Builder format where it returns itself) I think this would be nicer

After that it'd just be as simple as running the consumer in your inventoryClose method

**Comment by WesJD** [comment]
Until we get a true implementation of this, you can listen for InventoryCloseEvent and check if its the [anvil's inventory.](https://github.com/WesJD/AnvilGUI/blob/master/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L139)
