### ISSUE TITLE
Paper being removed from GUI

### ISSUE THREAD

**Issue by tchristofferson** [WesJD/AnvilGUI#36]
This is still happening for me in earlier versions, at least 1.9 and 1.10. Has the jar been updated since the commit? It seems like it maybe hasn't - navigating to the file in browser shows it was updated 3 days ago. 

Edit: I cloned the repo to get the updated code and it's fixed, but there's a problem where if I return a message, it removes the input paper and the same issue occurs so I have to close the inventory instead of using the error system.

_Originally posted by @Trophonix in https://github.com/WesJD/AnvilGUI/issues/32#issuecomment-508968637_

**Comment by tchristofferson** [comment]
This is happening when a player clicks the wrong slot.

**Comment by Trophonix** [comment]
Now I'm testing in 1.13.2 and I can take the paper out everytime I click through. I return null and when the inventory closes I am left with a paper.
