### ISSUE TITLE
Some way to disallow ESC-ing out of the AnvilGUI?

### ISSUE THREAD

**Issue by ThijmenL98** [WesJD/AnvilGUI#38]
See title:
Some way to disallow ESC-ing out of the AnvilGUI?

**Comment by WesJD** [comment]
Disallowing a user to escape out of the GUI is horrible user experience considering there's no buttons to close the GUI otherwise. Is there some specific reason you need to do this?

**Comment by Trophonix** [comment]
Well one reason I can think is if you want to make players type a password to join the server. Would be nice if you didn't have to re-open it or kick them if they fail.
