### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ThijmenL98** [WesJD/AnvilGUI#39]
On PaperMC version 1.14.3, i seem to not be able to find the AnvilGUI class, not sure why?

![](https://i.gyazo.com/8f800b9307bcf5de78cfc961df5db2b1.png)

![](https://i.gyazo.com/f192254f0f6e08a9eb8e8a6767a02e1b.png)

**Comment by Trophonix** [comment]
Did you compile it into your jar

**Comment by WesJD** [comment]
You need to shade it into your jar.
