### ISSUE TITLE
Not supported,latest spigot build?

### ISSUE THREAD

**Issue by ItzMikeGR** [WesJD/AnvilGUI#4]
Hey there,looks like the version I am using is not supported?I used the latest version(maven)

Maven:
![maven](https://cloud.githubusercontent.com/assets/19961621/21264051/cc0cd7f6-c3a2-11e6-8fb0-eaea03e59ece.jpg)

Error:
![npe](https://cloud.githubusercontent.com/assets/19961621/21264024/a168ad5e-c3a2-11e6-84f4-b489be7c24a3.jpg)

**Comment by WesJD** [comment]
On it.
