### ISSUE TITLE
Maven problem

### ISSUE THREAD

**Issue by ZakSmak** [WesJD/AnvilGUI#46]
Hey, I tried to add AnvilGUI to my project using maven. It says that version master-SNAPSHOT isn't available, only master-799c34ce7d-1.
Also when I try to compile the plugin with the AnvilGUI, it also compiles it with all Bukkit classes, so the compiled file size is like 31MB.

**Comment by WesJD** [comment]
Fixed compiling of Bukkit classes in 4b7a469

**Comment by ZakSmak** [comment]
Thank you. But still, when I try to add dependency to Maven, I only can see version master-799c34ce7d-1. Am I doing something wrong? I'm really sorry, but I never used Maven before, so I would be really glad if you could help.

**Comment by Nedjii** [comment]
Hello, i've got the same problem, it's not fixed yet !

**Comment by WesJD** [comment]
Looks like it needs to be `-SNAPSHOT` as the version. Jitpack seems to be a little misleading.

**Comment by ZakSmak** [comment]
-SNAPSHOT doesn't work, but **4b7a469d7e** as a version works.

**Comment by ZakSmak** [comment]
4b7a469d7e

**Comment by ZakSmak** [comment]
`4b7a469d7e`

**Comment by BONNe** [comment]
wesjd, you could try to add it in CodeMC build server.
They are welcoming everyone.

**Comment by zigazajc007** [comment]
Can't add code thru Maven

**Comment by iperuranio** [comment]
Same problem..

**Comment by BONNe** [comment]
```
	<dependency>
	    <groupId>com.github.WesJD.AnvilGUI</groupId>
	    <artifactId>anvilgui</artifactId>
	    <version>4b7a469d7e</version>
	</dependency>
```

This should work.

**Comment by WesJD** [comment]
Super odd. Does anyone know what version parameter is required for jitpack to get the latest release? Otherwise I might just link the jitpack page instead of providing the xml on the readme.
