### ISSUE TITLE
Second GUI support.

### ISSUE THREAD

**Issue by jb42300** [WesJD/AnvilGUI#47]
When using your resource to open a gui after you type out a reply. My inventories get messed up. my listener is ignored when I either close the inventory via ESC key, or when your AnvilGUI response.text is used.

Example: 
either escaping the inventory via esc key, or a anvilgui.response.text return statement
https://i.imgur.com/zKgOI4w.png

My listener then gets ignored:
https://i.imgur.com/SCxSq8l.png

When my GUI is supposed to look like this
https://i.imgur.com/JtuM7Vc.png

I've had problems in the past as well trying to open guis with your resource in the earlier versions as well. Getting these errors:
 https://i.imgur.com/LTA1ZMa.png

Thanks! 
This resource is great.

**Comment by jb42300** [comment]
`if (e.getClick().equals(ClickType.LEFT)) {
					new AnvilGUI.Builder()
				    .onClose(player -> {
				    	List<Inventory> invs = Helpop.inv.get(player.getUniqueId());
						player.openInventory(invs.get(0));
				    })
				    .onComplete((player, text) -> {
				        if(!(text.split(" ").length < 3)) {
				        	HelpopSearch.contentSearch.put(player.getUniqueId(), text);
							HelpopSearch.refresh(player);
							player.openInventory(HelpopSearch.invs.get(p.getUniqueId()));
				            return AnvilGUI.Response.close();
				        } else {
				            return AnvilGUI.Response.text("Enter more then 3 words");
				        }
				    })
				    .text("content")
				    .plugin(Core.plugin)
				    .open(p);               
					return;
				}`

**Comment by jb42300** [comment]
> if (e.getClick().equals(ClickType.LEFT)) {
					new AnvilGUI.Builder()
				    .onClose(player -> {
				    	List<Inventory> invs = Helpop.inv.get(player.getUniqueId());
						player.openInventory(invs.get(0));
				    })
				    .onComplete((player, text) -> {
				        if(!(text.split(" ").length < 3)) {
				        	HelpopSearch.contentSearch.put(player.getUniqueId(), text);
							HelpopSearch.refresh(player);
							player.openInventory(HelpopSearch.invs.get(p.getUniqueId()));
				            return AnvilGUI.Response.close();
				        } else {
				            return AnvilGUI.Response.text("Enter more then 3 words");
				        }
				    })
				    .text("content")
				    .plugin(Core.plugin)
				    .open(p);               
					return;
				}

**Comment by jb42300** [comment]
https://pastebin.com/rxZdWQPB

**Comment by WesJD** [comment]
You're getting the "You can't close an inventory that isn't open!" because quite literally, you've already closed the anvil gui before you respond with Response#close().

**Comment by jb42300** [comment]
LOL. it's amazing what opening your eyes does. Thanks.
