### ISSUE TITLE
Blank anvil (Spigot 1.15/1.15.1)

### ISSUE THREAD

**Issue by einTosti** [WesJD/AnvilGUI#60]
Hey, 
when i create an anvil using this code: https://hastebin.com/oqoqujijis.coffeescript
it only creates a "blank' anvil (without an item), therefore nothing can be rename.
No errors are thrown.
<img width="530" alt="Screenshot 2019-12-28 at 23 46 03" src="https://user-images.githubusercontent.com/29168243/71550269-6b63ef00-29cc-11ea-834f-5917b74b950a.png">

**Comment by WesJD** [comment]
@mastercake10

**Comment by mastercake10** [comment]
Your link does not seem to work. Can you post your code here instead?

**Comment by einTosti** [comment]
It actually turned out to be a bug with the Badlion Client.
Therefore everything if fine with the plugin.
**#closed**
