### ISSUE TITLE
onClose not working properly

### ISSUE THREAD

**Issue by HMJosh** [WesJD/AnvilGUI#64]
Hey, just having a problem with the onClose part of the builder of AnvilGUI

I'm using this:

`new AnvilGUI.Builder()
			    .onClose(player -> {
			    	new BukkitRunnable() {
		        		public void run() {
		        			List<Inventory> invs = Helpop.inv.get(player.getUniqueId());
		        			player.openInventory(invs.get(0));
		        		}
		        	}.runTaskLater(Core.plugin, 1);
			    })
			    .onComplete((player, text) -> {
			    	if(Assets.isNumeric(text)) {
			    		int id = Integer.valueOf(text);
						if(!Assets.senderName.containsKey(id)) {
							return AnvilGUI.Response.text("Invalid ticket");
						}
						new BukkitRunnable() {
			        		public void run() {
			        			new HelpopAdminManager(id);
								player.openInventory(HelpopAdminManager.map.get(id));
			        		}
			        	}.runTaskLater(Core.plugin, 1);
			        	return AnvilGUI.Response.close();
			    	} else {
			    		return AnvilGUI.Response.text("Numerical ids only");
			    	}
			    })
			    .text("id")
			    .plugin(Core.plugin)
			    .open(p);`

however, when I put in my value (that is valid) and click next, it just acts like I closed the GUI.

I reverted a few versions back and fixes it but causes a separate problem haha. (I use 478e0c1 now)

Nice resource, I use it on all my GUI plugins. 

Any other questions just dm me on discord: Joshb_#0001

**Comment by HMJosh** [comment]
Sorry, here is a formatted code link: https://pastebin.com/bgZdHiV7

**Comment by WesJD** [comment]
What do you mean by `click next`?

**Comment by HMJosh** [comment]
When I submit the response. The paper on the bottom right that sends onComplete

**Comment by WesJD** [comment]
Looks like AnvilGUI is calling Player#closeInventory() at the same time you are opening your inventory.
