### ISSUE TITLE
.item(ItemStack) not adding item with name/lore

### ISSUE THREAD

**Issue by Broanater** [WesJD/AnvilGUI#67]
With the code below the item is given to the player as it should be with name and lore. But the item within the anvilGUI once opened is not the same item as the one given. I am using <version>99a504a3bb</version>.
```
myPlayer.getInventory().addItem(item);
new AnvilGUI.Builder()
    .onComplete((player, text) ->
    {
        String cmdStr = anvilCommand.getCommand().replace("%args%", text);
        player.performCommand(cmdStr);
									
        return AnvilGUI.Response.close();
    })
    .item(item)
    .plugin(plugin)
    .open(myPlayer);
```

**Comment by WesJD** [comment]
What Minecraft version are you using?

**Comment by Broanater** [comment]
1.12.2

________________________________

**Comment by WesJD** [comment]
Could you describe what you mean by `is not the same item as the one given`? I cannot reproduce the item not being the same.

**Comment by Broanater** [comment]
The give item before populates the item with custom name and lore. When entering the item into the anvil there is no custom name and no custom lore. Just the default item.

________________________________

**Comment by WesJD** [comment]
I'm using the following code on 1.12.2 and cannot reproduce what you're describing.

```java
ItemStack stack = new ItemStack(Material.EMERALD_BLOCK);
ItemMeta meta = stack.getItemMeta();
meta.setDisplayName(RED + "My Custom Item");
meta.setLore(Arrays.asList("Hi there", "this is lore"));
stack.setItemMeta(meta);

new AnvilGUI.Builder()
        .onComplete((thePlayer, text) -> {
            thePlayer.sendMessage("You said: " + text);
            return AnvilGUI.Response.close();
        })
        .item(stack)
        .plugin(this)
        .open(player);
```

**Comment by Broanater** [comment]
Apologies for the delay as I was on vacation. I copied your method and pasted it into my code. The lore is now being populated however the name is still missing.
