### ISSUE TITLE
Shift-clicking inventory items locks them in second anvil slot

### ISSUE THREAD

**Issue by Erlebsyk** [WesJD/AnvilGUI#70]
**Description**
I've noticed a bug where inventory items are permanently lost if the anvil GUI is not used correctly. If any inventory item is shift-cliked while using the GUI, the item is inserted into the second slot and can no longer be returned to the player. Example [video](https://youtu.be/N4xyhTjvHqc). The example shown in the video is when using the [waypoints](https://www.spigotmc.org/resources/waypoints.66647/) plugin, which uses this library. I submitted the [same issue](https://github.com/Sytm/waypoints2/issues/12) to that plugin, but was redirected here.

**Impact**
This is not an issue with normal use, however it can be very unfortunate if valuable items are lost if someone accidentally shift-clicks one of their items.

**Steps to reproduce**
Using waypoints (or another plugin depending on this library I suppose): Open GUI, add new waypoint or folder to open anvil GUI, then shift-click an item within the inventory to insert it into the second anvil slot. It is also possible to insert an item into the second anvil slot by repeatedly left-clicking it with a selected item. The inserted item can then no longer be returned and will be permanently lost after exiting the gui.

**System**
Java 1.8
Minecraft version 1.15.2
Paper latest version (for now anyway): Paper-121 (API version 1.15.2-R0.1-SNAPSHOT)
Waypoints plugin version: 2.6.1

**Error logs**
No logs or errors displayed in console.

I'm not a plugin developer, so unfortunately I can't provide any technical details regarding the code using the GUI.

**Comment by WesJD** [comment]
I appreciate the detailed issue. This issue will be fixed in #62. Please remind the plugin developer to update the plugin once I merge that PR in a few minutes.
