### ISSUE TITLE
I want the text to empty, but It doesn't works

### ISSUE THREAD

**Issue by hufskhj1** [WesJD/AnvilGUI#74]
I want make the text to empty. but using .text("") is not working.
If I use .text(""), it just print Material name ex(Name tag, Paper, Glass, ...)

how can i do?

new AnvilGUI.Builder()
                .onComplete((player, text) -> {
                    if(Login.getPasswordEquals(p, text)) {
                        player.sendMessage(ChatColor.RED + "Login!");
                        return AnvilGUI.Response.close();
                    } else {
                        p.kickPlayer(ChatColor.RED + "[YLogin] no.");
                        return AnvilGUI.Response.close();
                    }
                })
                .preventClose()
                .item(new ItemStack(Material.PAPER))
                .text("")
                .title(ChatColor.RED + "Login")
                .plugin(Main.getPlugin(Main.class))
                .open(p);

**Comment by portlek** [comment]
Can you put your codes into;
![image](https://user-images.githubusercontent.com/12835420/76954253-18416e80-6921-11ea-9605-e6f11f8c4459.png)

**Comment by hufskhj1** [comment]
Temporarily, although the code has been changed as shown below, renaming using meta.setDisplayName() does not work at all (without .text(), only use meta. with .text("Something") is work.)
But .text("") does not work, on the other hand .text("Something") work

```java
public static void openLoginGUI(Player p) {

        ItemStack item = new ItemStack(Material.NAME_TAG);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("Enter your password");
        //meta.setLore(Arrays.asList());
        item.setItemMeta(meta);

        new AnvilGUI.Builder()
                .onComplete((player, text) -> {
                    if(Login.getPasswordEquals(p, text)) {
                        player.sendMessage(ChatColor.RED + "Login!");
                        return AnvilGUI.Response.close();
                    } else {
                        p.kickPlayer(ChatColor.RED + "[YLogin] Incorrect Password");
                        return AnvilGUI.Response.close();
                    }
                })
                .preventClose()
                .item(item)
                .text("Enter your password")
                .title(ChatColor.RED + "Login")
                .plugin(Main.getPlugin(Main.class))
                .open(p);

    }
````

**Comment by hufskhj1** [comment]
> Can you put your codes into;
> ![image](https://user-images.githubusercontent.com/12835420/76954253-18416e80-6921-11ea-9605-e6f11f8c4459.png)

Plz see up. thankyou

**Comment by portlek** [comment]
I guess the problem is that you are using item and text method at the same time so, i think you should remove text method from the builder and try to use just item method for renaming.

**Comment by hufskhj1** [comment]
> I guess the problem is that you are using item and text method at the same time so, i think you should remove text method from the builder and try to use just item method for renaming.

I already have tested that.

removing text method and using just item method does not work at all
lore work, but name is not work. In game, that display just Material Name. (Name tag, Paper, ...)
Not using itemmeta, and using .text does only work.

**Comment by WesJD** [comment]
Bukkit does not support naming items `""`. You need to put a space for it to be emtpy: `" "`.
