### ISSUE TITLE
Cancel Function

### ISSUE THREAD

**Issue by Tanju42** [WesJD/AnvilGUI#75]
When the Player klicks the 3rd item then onComplete gets called.
so when the player klicks the first item then onCancel should get called becouse I have no idea how the player should cancel what he is doing. And I really need this function and please don´t close this so fast and help me pls

**Comment by portlek** [comment]
Player can close the menu? So it means cancelling BUT, if you click the 3rd button it will close the menu also(depends on your code text() or close() responses). You can add some properties if player click 3rd add xxx to the player properties and if it didn't click 3rd button and close the menu there is no xxx value on the player properties so it means the whole situation was cancelled. You can do that easily :)

**Comment by Tanju42** [comment]
can you give me an example becouse when I do that my inventory from SmartInvs gets broken :K

**Comment by Tanju42** [comment]
*push* @portlek

**Comment by portlek** [comment]
```java
private final Map<Player, String> properties = new HashMap<>();
anvilBuilder()
  .otherMethods
  .closeMethod(closer -> {
    final String property = properties.get(closer);
  }).completeMethod((clicker, s) -> {
    properties.put(clicker, s);
    return close();
  })
  .open(player);
```

**Comment by WesJD** [comment]
I've already stated that if you want to do this, you will not be provided support. Stop opening new issues.
