### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iGabyTM** [WesJD/AnvilGUI#76]
Would be possible to let the user add their own item in the first slot and then give it the custom name typed on the text box? Also, does the text box support colors?

**Comment by WesJD** [comment]
So you want to have it be a regular anvil? Just open a normal anvil inventory then. If you need support colors, just listen to InventoryClickEvent and translate the name's color codes.

**Comment by iGabyTM** [comment]
I was hopping I can use yours because I'm not a fan of NMS, thank you anyways.

**Comment by WesJD** [comment]
You don't need to use NMS to open an anvil gui. You need NMS for this library in order to control how XP is handled, etc.

**Comment by iGabyTM** [comment]
Would be possible to not give the item when the inventory is closed? Or at least to access it in order to  set the name colors.

**Comment by iGabyTM** [comment]
Using `Player#getOpenInventory()` to set the result item to `null` worked.
