### ISSUE TITLE
ClassNotFoundException maven

### ISSUE THREAD

**Issue by BanjerHD** [WesJD/AnvilGUI#8]
Hello, I have a problem with your api.
I am trying to build it within Eclipse, and it builds just fine but if I try to use it on my server it throws an ClassNotFoundException.

pom.xml: https://pastebin.com/m6MPRwFr
Usage: https://pastebin.com/euf62CeY

Thanks for reading!

EDIT: Do you need to install this plugin on your server for it to work?

**Comment by WesJD** [comment]
What server version are you using? Also, please supply the error you are getting.

**Comment by BanjerHD** [comment]
Thanks so much for your quick answer!

I am using spigot 1.12.
My error: https://pastebin.com/ycz5JnVQ
Line 29 is
> new AnvilGUI(main, e.getPlayer(), "Name your team", (player, reply) -> {

And my anvil opens when I place a beacon.

**Comment by WesJD** [comment]
You are not shading the AnvilGUi jar into yours.

**Comment by BanjerHD** [comment]
How do I?

**Comment by BanjerHD** [comment]
Oops I readed it wrong, I actualy have it in my pom but how do I shade it?

My pom:
https://pastebin.com/m6MPRwF
