### ISSUE TITLE
Inventory does not refresh

### ISSUE THREAD

**Issue by hufskhj1** [WesJD/AnvilGUI#80]
After you close the AnvilGUI, the inventory stops. After you pick up an item, the inventory does not change, but only when you go out and come back in, the inventory refreshes and displays properly.

**Comment by WesJD** [comment]
Could you provide some code or something? Your explanation makes no sense.

**Comment by hufskhj1** [comment]
`java
package yeev.newtest;

import net.wesjd.anvilgui.AnvilGUI;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.inventory.ItemStack;

public class event implements Listener {

    @EventHandler
    private void onPlayerJoin(PlayerJoinEvent e) {

        Player p = e.getPlayer();

        new AnvilGUI.Builder()
                .onClose(player -> {                      //called when the inventory is closing
                    player.sendMessage("You closed the inventory.");
                })
                .onComplete((player, text) -> {           //called when the inventory output slot is clicked
                    if(text.equalsIgnoreCase("you")) {
                        player.sendMessage("You have magical powers!");
                        return AnvilGUI.Response.close();
                    } else {
                        return AnvilGUI.Response.text("Incorrect.");
                    }
                })
                .preventClose()                           //prevents the inventory from being closed
                .text("What is the meaning of life?")     //sets the text the GUI should start with
                .item(new ItemStack(Material.GOLD_BLOCK)) //use a custom item for the first slot
                .title("Enter your answer.")              //set the title of the GUI (only works in 1.14+)
                .plugin(Newtest.getPlugin(Newtest.class))                 //set the plugin instance
                .open(p);                          //opens the GUI for the player provided

    }

}

`

**Comment by hufskhj1** [comment]
> Could you provide some code or something? Your explanation makes no sense.

My code is just your example

I'm using Paper-api 1.15.2. Maybe there is problem?


`package yeev.newtest;

import net.wesjd.anvilgui.AnvilGUI;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.inventory.ItemStack;

public class event implements Listener {

    @EventHandler
    private void onPlayerJoin(PlayerJoinEvent e) {

        Player p = e.getPlayer();

        new AnvilGUI.Builder()
                .onClose(player -> {                      //called when the inventory is closing
                    player.sendMessage("You closed the inventory.");
                })
                .onComplete((player, text) -> {           //called when the inventory output slot is clicked
                    if(text.equalsIgnoreCase("you")) {
                        player.sendMessage("You have magical powers!");
                        return AnvilGUI.Response.close();
                    } else {
                        return AnvilGUI.Response.text("Incorrect.");
                    }
                })
                .preventClose()                           //prevents the inventory from being closed
                .text("What is the meaning of life?")     //sets the text the GUI should start with
                .item(new ItemStack(Material.GOLD_BLOCK)) //use a custom item for the first slot
                .title("Enter your answer.")              //set the title of the GUI (only works in 1.14+)
                .plugin(Newtest.getPlugin(Newtest.class))                 //set the plugin instance
                .open(p);                          //opens the GUI for the player provided

    }

}
`

**Comment by portlek** [comment]
Please put the code like that
![image](https://user-images.githubusercontent.com/12835420/78660107-31608e00-78d5-11ea-87b4-075b4e053dfb.png)

**Comment by WesJD** [comment]
@hufskhj1 Could you please explain the problem clearly?

**Comment by portlek** [comment]
Are you trying to open an inventory in onClose method?

**Comment by hufskhj1** [comment]
> @hufskhj1 Could you please explain the problem clearly?

I fixed this problem.

I add the 1 tick before opening anvil gui on player join event.
then, that is fixed
