### ISSUE TITLE
Multiple Open AnvilGUIs open causes issues

### ISSUE THREAD

**Issue by orlaaando** [WesJD/AnvilGUI#81]
There is an issue where if there is more than one instance of the AnvilGUI open it seems to bug out a bit. 

For example, player1 has anvilgui1 open, and player2 has anvilgui2 open.

player2 clicks the paper in anvilgui2, it closes anvilgui1 AND anvilgui2 and fires the event for both

**Comment by Oscaz** [comment]
Provide a version and your code please. It's impossible to say without seeing what you've done.

**Comment by orlaaando** [comment]
I'm on the latest version, my code is what is identical to what is on the example page.

**Comment by WesJD** [comment]
Please provide your code. Unless you're doing something really wacky, AnvilGUI instances have no knowledge of each other, meaning that what your describing is impossible without some sort of external code modifying it (i.e. a plugin).

**Comment by Orlaando-dev** [comment]
Sorry for the late response. However here is my code-
https://pastebin.com/1mTPK3Ka
