### ISSUE TITLE
Add Response fireEvent

### ISSUE THREAD

**Issue by xXSchrandXx** [WesJD/AnvilGUI#82]
Hi,

I'm new in using your code, but a [Response ](https://github.com/WesJD/AnvilGUI/blob/7a87a9dd652fcb7ff323f6bd8bd751ab1e6c2db6/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L388) wich just fires the [InventoryClickEvent ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryClickEvent.html) and doing nothing else would help me.
Because I'm swapping the Inventorys with my plugin many times, I would love to listen like in my other Menus.

My code: https://github.com/xXSchrandXx/SpigotPlugins/blob/master/AsyncWorldManagerGUI/src/main/java/de/xxschrandxx/awm/gui/menus/ModifierMenu.java

**Comment by WesJD** [comment]
This is unneeded. You can't open and close an inventory in the same tick anyways. In the onComplete handler, just wait a tick before opening your other menu.
