### ISSUE TITLE
Colour doesn't work on item

### ISSUE THREAD

**Issue by Jaffaaaa** [WesJD/AnvilGUI#91]
![image](https://user-images.githubusercontent.com/39811887/84388313-46ff7600-abec-11ea-8e3c-8a403525f0fa.png)
I'm currently using 1.8.8. The colour works for a second after entering an input then after a second or to undoes the format

Edit: Also the title for the gui doesn't work. Not sure if this is an issue with the code or a 1.8 limitation

**Comment by portlek** [comment]
can you show what the code you wrote.

**Comment by Jaffaaaa** [comment]
``vars.priceGuiTitle`` returns ``Util.color(&aEnter new price:)`` and ``vars.priceGuiFirstLinePrefix`` returns ``Util.color("&6$&e100.00");``
```java
new AnvilGUI.Builder()
    .onClose(player -> {
          player.playSound(player.getLocation(), Sounds.BASS, 1, 1);
          TempAuctionManager.setChangingGUI(player.getUniqueId());
          new BukkitRunnable() {
                 @Override
                 public void run() {
                      CreateAucGUI.openInventory(player);
                  }
             }.runTaskLater(core, 5);
       })
       .onComplete((player, text) -> {
             System.out.println("true");
             return AnvilGUI.Response.close();
       })
       .item(new ItemStack(Material.PAPER, 1))
       .plugin(core)
       .title(vars.priceGuiTitle)
       .text(vars.priceGuiFirstLinePrefix)
       .open(target);

**Comment by Jaffaaaa** [comment]
@portlek Any idea on a fix? I appreciate this being free so if you don't have the time I understand

**Comment by portlek** [comment]
I will test the code ASAP. I didn't use the item with color codes but I guess I was working.

**Comment by WesJD** [comment]
This seems highly plausible to be a modified client or a modified server jar. The output item is generated by the server itself, not our library.

**Comment by Jaffaaaa** [comment]
Sorry for replying so late. I'm using a completely vanilla client and the latest stable version of spigot with no plugins other than the one I'm making. Plus when I output the value, it still comes out like this:
![image](https://user-images.githubusercontent.com/39811887/86502011-73935180-bd96-11ea-998c-13fb5e03f2ee.png)
