### ISSUE TITLE
First slot?

### ISSUE THREAD

**Issue by MineVid** [WesJD/AnvilGUI#92]
Hello there,
First of all this is great API! 
I have a question: is it possible to have a listener when the first slot is clicked to make some kind of cancel button. Tries with the onClose when the inputted value is null doesn't seem to work right for me. I can open my inventories but however they lose there functions for some odd reason. 
I think listening when the first slot is clicked would fix this issue. 
Kind regards!

**Comment by jmanpenilla** [comment]
Try re-opening your inventory one tick later using the Bukkit scheduler

**Comment by WesJD** [comment]
Unfortunately, I'm quite certain that the client does the arrow equality checks on its own. Therefore, having two items that are different would display a red X, which is an even worse user experience. If anyone has more info on this (I might be mistaken), please feel free to comment.
