### ISSUE TITLE
$Response does not exist error

### ISSUE THREAD

**Issue by MCArTyR** [WesJD/AnvilGUI#95]
`Plugin Test v1.0-SNAPSHOT has failed to register events for class me.mcartyr.Test.Events.EventsClass because net/wesjd/anvilgui/AnvilGUI$Response does not exist.`
I'm clone this repo and build with maven
`mvn install`
How to fix it?

**Comment by MCArTyR** [comment]
I also tried to add a jitpack to the repositories, and anvilgui dependencies. The problem is the same.

**Comment by portlek** [comment]
can you show your pom.xml file

**Comment by MCArTyR** [comment]
What for? I'm telling you that i build a .jar file and imported it into the project through eclipse.
`<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>me.mcartyr.Tutorial2</groupId>
  <artifactId>Tutorial2</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <name>Tutorial2</name>
  
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
`

**Comment by Sytm** [comment]
Looks like you are not properly using maven. You do not need to import the jars into eclipse, you just define the dependencies in the pom.xml and the will be imported if set up properly.

Then I'd recommend looking at the maven shade plugin, which is required for your use case. This maven plugin takes your jar and the AnvilGUI jar and merges them together, so you get one "fat" jar as the final output that is more or less standalone

**Comment by MCArTyR** [comment]
I know that I can just add a dependency to the pom.I've already tried xml. The error is the same, after that I already tried to import it .jar, the error has not changed

**Comment by Sytm** [comment]
You dont want to **import** the jar, you want to **shade** the jar using maven.

**Comment by MCArTyR** [comment]
OK, and how does this fix my problem?

**Comment by Sytm** [comment]
Well, if AnvilGUI is shaded into your final plugin jar, it cannot be missing
