### ISSUE TITLE
Players cannot use any inventories while an anvil GUI is open

### ISSUE THREAD

**Issue by darcros** [WesJD/AnvilGUI#99]
As the title says, whenever a player has an AnvilGUI open all other players cannot use any inventories.

I have taken a look at the source code and I found out that the `net.wesjd.anvilgui.AnvilGUI.ListenUp` listener cancels all `InventoryClickEvent` events, making inventories effectively unusable. I have also verified with a debugger that this is the case.

I don't get why this condition was written the way it is, we should not act on events that are not originating from the anvil inventory
https://github.com/WesJD/AnvilGUI/blob/ef71db62ecd6e14405eb7891d7d1c58341b9e61e/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L207-L211

in this previous commit it made more sense
https://github.com/WesJD/AnvilGUI/blob/3e424a33a3fc25895d142ad1efadca5879adb945/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L195

Maybe I'm missing something and there is a reason for all the other checks, but the way it is right now it's canceling events on all inventories regardless of the player using it.

**Comment by WesJD** [comment]
Yeah, it seems like someone who submitted a PR for that change messed up the conditions. Could you submit a PR that requires the inventories to be equal? If not, I'll do it when I get a chance.
